"""Onboarding step IDs and status values (product + API)."""

from __future__ import annotations

STEP_WELCOME = "WELCOME"
STEP_COMPANY_INFO = "COMPANY_INFO"
STEP_TOOL_STACK_DISCOVERY = "TOOL_STACK_DISCOVERY"
STEP_TOOLS_SELECTION = "TOOLS_SELECTION"
STEP_CONNECT_GITHUB = "CONNECT_GITHUB"
STEP_CONNECT_LINEAR = "CONNECT_LINEAR"
STEP_SCANNING = "SCANNING"
STEP_THANK_YOU = "THANK_YOU"

ONBOARDING_STEPS: frozenset[str] = frozenset(
    {
        STEP_WELCOME,
        STEP_COMPANY_INFO,
        STEP_TOOL_STACK_DISCOVERY,
        STEP_TOOLS_SELECTION,
        STEP_CONNECT_GITHUB,
        STEP_CONNECT_LINEAR,
        STEP_SCANNING,
        STEP_THANK_YOU,
    },
)

STATUS_IN_PROGRESS = "in_progress"
STATUS_COMPLETED = "completed"
STATUS_ABANDONED = "abandoned"
