"""Phase 06 — Temporal & causal execution reconstruction (TCRE).

P06-01: ``normative.PHASE06_PROGRAM_FREEZE_VERSION`` (``phase-06-normative-index.md``).
P06-02: ``anti_goals`` — forbidden cognition keys + ``G-P06-ANTI-01`` package import scan
(``phase-06-anti-goals-doctrine.md``).
P06-03: ``execution_causality_constraints`` — observed vs derived boundary +
``TCRECausalEdge_v1`` stub law (``execution-causality-constraints.md``).
P06-04: ``organizational_continuity_reasoning`` — Phase **04** continuity as evidence + walk handoff
(``organizational-continuity-reasoning.md``).
P06-05: ``temporal_reasoning`` — intervals, anchors, half-open law, T‑TEMP‑* invariants
(``temporal-reasoning-doctrine.md``).
P06-06: ``chronology_legality`` — ``chronology_skew_projection_v1`` + **CHRON‑FORB‑1**
(``chronology-legality-law.md``, ``chronology-replay-legality-state-machine.md``).
P06-07: ``temporal_anchor_resolution`` — normalize +
``temporal_anchor_resolution_order_v1`` + receipts (``temporal-anchor-resolution-spec.md``).
P06-08: ``interval_continuity`` — half-open chain closure + ``reasoning_chronology_receipt`` binding
(``temporal-reasoning-doctrine.md``, ``chronology-replay-legality-state-machine.md``).
P06-09: ``replay_chronology`` — pinned replay tuple +
``reasoning_replay_permutation_v1`` + tuple bridge
(``replay-aware-reasoning-law.md``, ``replay-equivalence-reasoning-spec.md``).
P06-10: ``temporal_conflict_resolution`` — late arrival / skew / export vs observed +
precedence ladder (``temporal-conflict-resolution-law.md``).
P06-11: ``chronology_degradation_propagation`` — ``CD‑CHRON`` propagation,
corpus ``CD‑*`` normalization, policy caps (**G‑P06‑POL‑01** sketch), **DEG‑MON‑1** ordering
(``causal-degradation-spec.md``, ``chronology-replay-legality-state-machine.md`` §6).
P06-12: ``cross_system_time_reconciliation`` — ``rank(S)`` ladder, **CROSS‑CAUS‑1/2**, policy
``cross_system_causal_min_rank`` (floor **4**), chronology strict-order gate, typed skew tuple
(``cross-system-causal-continuity.md``, ``chronology-legality-law.md``).
P06-13: ``causal_interval_closure`` — half-open causal influence interval chains, **hop** /
**breakpoint** caps from policy, lexicographic canonical ``tcre_edges`` id list
(``deterministic-causal-chain-spec.md``, ``reasoning-policy-pack-v1.md``).
P06-14: ``causal_reconstruction_substrate`` — Option **A**
``TCRECausalEdge_v1`` vs ``ExecutionCoordinationEdge``, closed enum wiring,
``confidence_source``, registry §5 cross-system weak guard
(``causal-reconstruction-doctrine.md``, ``tcre-causal-edge-registry-v1.md``).
P06-15: ``deterministic_causal_chain`` — ``causal_chain_id`` canonical JSON + **sha256**;
**must** include ``tcre_policy_bundle_digest`` (``deterministic-causal-chain-spec.md`` §1).
P06-16: ``causal_propagation_policy`` — ``merge_rules_coordination_edges`` (**M‑INJ‑1** caps),
optional ``propagation_rule_table_v1``, combined **P06-03** stub + policy merge caps
(``causal-reconstruction-doctrine.md`` §4, ``reasoning-policy-pack-v1.md``).
P06-17: ``causal_graph_ownership_continuity`` — authoritative Phase **04** ``org_link_support`` when
``underlying_coordination_edge_ids`` cite coordination; substrate lineage + sole-support law
(``organizational-continuity-reasoning.md`` §2, ``tcre-causal-edge-registry-v1.md``).
P06-18: ``commitment_derived_causality`` — ``tcre_commitment_transition`` derivation prefix + §4.2
sentinel lineage (raw + ``commitment_id`` on hops) + P06-14 combined entry
(``causal-reconstruction-doctrine.md``, ``tcre-causal-edge-registry-v1.md``).
P06-19: ``negative_signal_causality`` — ``tcre_negative_signal`` derivation prefix,
``silence-causality-law.md`` §1 ``NegativeSignalKind`` allowlist, §4.2 sentinel lineage
(raw + ``signal_id``) + P06-14 combined entry
(``causal-reconstruction-doctrine.md``, ``tcre-causal-edge-registry-v1.md``,
``silence-causality-law.md``).
P06-20: ``execution_causality_constraints`` §4 — closed ``causal_legality_class`` literals +
``CAUSAL_LEGALITY_ENUM_VERSION_V1``; ``validate_tcre_edge_v1_stub`` checks the field when present;
``verify_gp06_clc01``…``verify_gp06_clc04`` (``execution-causality-constraints.md``,
``tcre-causal-edge-registry-v1.md`` §7).
P06-21: ``replay_safe_reasoning_posture`` — pinned tuple (A–E) + **sha256**
``tcre_policy_bundle_digest`` (C) per ``reasoning-policy-pack-v1`` before ``replay_chronology``
tuple law; permutation profile id; ``verify_gp06_rsp01``…``verify_gp06_rsp04``
(``replay-aware-reasoning-law.md`` §1, ``reasoning-policy-pack-v1.md``).
P06-22: ``causal_ambiguity_propagation`` — ``AMB‑*`` registry + §3 corpus aliases
(**G‑P06‑AMB‑01**), ``AMB‑S1`` coercion flags; ``verify_gp06_amb01``…``verify_gp06_amb05``
(``bounded-ambiguity-law.md``, ``ambiguity-registry-v1.md``, conflict-resolution §5).
P06-23: ``unverifiable_degraded_causality`` — ``causal_unverifiable`` **requires** non-empty
``CD‑*`` multiset evidence; **DEG‑MON‑1** multiset monotonicity + §4 receipt sort (compose P06-11
+ P06-20); ``verify_gp06_udc01``…``verify_gp06_udc05`` (``causal-degradation-spec.md``,
``execution-causality-constraints.md``, conflict-resolution §6 supersession note).
P06-24: ``reasoning_provenance_law`` — §1 mandatory envelope (provenance hops, replay posture,
chronology + causal legality, ``DeterministicConfidenceSource``, ``AMB‑*``, cross-system
``org_link_support``, sorted ``cd_codes`` + optional ``degradation_coarse``); rejects legacy
``degradation_semantics`` vague tags; ``verify_gp06_rpl01``…``verify_gp06_rpl05``
(``reasoning-provenance-law.md``, golden-thread §5).
P06-25: ``reasoning_receipts_proof_artifacts`` — §1 receipt kinds + ``REASONING_RECEIPT_TYPES_V1``,
``REASONING_CANON_VERSION_V1``, canonical JSON **sha256**
(``hash_reasoning_canonical_json_sha256_v1``),
``reasoning_{causal,ambiguity,equivalence}_receipt_body_v1``;
``verify_gp06_rra01``…``verify_gp06_rra05``
(``reasoning-receipts-and-proof-artifacts.md``).
P06-26: ``replay_equivalence_proofs`` — **``G‑P06‑REPLAY‑01``** frozen digest comparison vector
(``normalize_gp06_replay_01_comparison_vector_v1``, ``compare_gp06_replay_01_double_run_v1``),
``reasoning_replay_permutation_v1`` profile id cross-check, §2 causal-only insufficiency law;
``verify_gp06_req01``…``verify_gp06_req06``
(``replay-equivalence-reasoning-spec.md`` §2–3, ``replay-aware-reasoning-law.md`` §1).
P06-27: ``causal_drift_proofs`` — ``causal-breakpoint-detection-spec`` §5 ``breakpoint_id`` +
deterministic ``breakpoint_index`` sort, drift / degradation receipt ↔ breakpoint rule coverage;
``verify_gp06_cdp01``…``verify_gp06_cdp05``
(``causal-degradation-spec.md``, ``deterministic-causal-chain`` digest).
P06-28: ``proof_bundle_composition`` — inner proof bundle **sha256** over canonical sorted
``(receipt_type, digest)`` rows + ``reasoning_canon_version_v1``; §2 **equivalence receipt set**
(required kinds vs ``chronology_participates`` / ``ambiguity_active`` / ``walk_consumed``);
``verify_gp06_pbc01``…``verify_gp06_pbc05``
(``reasoning-receipts-and-proof-artifacts.md`` §2, ``replay-equivalence-reasoning-spec.md`` §2).
P06-29: ``reasoning_verification_harness`` — **G-P06-*** gate catalog + **STAGE-A…Z** map,
``run_reasoning_gp06_wired_verification_stages_v1`` and
``run_reasoning_gp06_pr_blocking_static_stages_v1``,
``verify_gp06_rvh01``…``verify_gp06_rvh03``
(``reasoning-verification-harness-spec.md`` §1).
P06-30: ``reasoning_golden_thread_binding`` — on-disk **golden-thread** corpus under
``reasoning_golden_vectors/v1`` (``corpus_manifest.json`` + ``cases/*/case.json``);
``AMB‑*`` / ``CD‑*`` / optional ``expected_tcre_causal_chains`` binding;
``verify_gp06_gtc01``…``verify_gp06_gtc05``
(``golden-thread-replay-corpus-spec.md`` §§2–3, ``reasoning-verification-harness-spec.md`` §2).
P06-31: ``reasoning_ci_enforcement_architecture`` — full **STAGE-A…Z** row map (empty rows
permitted), **PR-blocking** stage constants, meta + topology runners;
``verify_gp06_cia01``…``verify_gp06_cia08``
(``reasoning-verification-harness-spec.md`` §Staging;
``05-traversal/phase-05-ci-enforcement-architecture.md`` topology mirror).
P06-32: ``reasoning_control_plane`` — admin **control plane** catalog (**§1** mandatory surfaces),
``GET .../cortex/reasoning/control-plane``, doctrine + RBAC pointers;
``verify_gp06_rcp01``…``verify_gp06_rcp06``
(``reasoning-admin-control-plane-spec.md``).
P06-33: ``reasoning_runtime_legality_matrix`` — **R‑LEG‑01..05** catalog + forbidden deployments +
waiver path literal; **R‑LEG‑02** wired to **G‑P06‑ANTI‑01** static oracle;
``GET .../cortex/reasoning/runtime-legality-matrix``;
``verify_gp06_rlm01``…``verify_gp06_rlm07``
(``reasoning-runtime-legality-matrix.md``).
P06-34: ``reasoning_tenant_verification_slice`` + ``reasoning_readiness_economics`` — bounded
**``org_graph_reasoning``** aggregate (integer-only) + economics probes over golden-thread corpus
(**FS‑RTV‑01** /
**FS‑RECO‑01**); admin ``GET .../cortex/reasoning/tenant-verification-slice`` and
``GET .../cortex/reasoning/readiness-economics``;
``verify_gp06_rtvs01``…``verify_gp06_rtvs02``, ``verify_gp06_rreco01``…``verify_gp06_rreco03``
(``reasoning-verification-harness-spec.md``, ``reasoning-admin-control-plane-spec.md``).
P06-35: ``reasoning_certification_pack`` — **TCRE-CERT-PACK-1** parity with **OCTS-CERT-PACK-1**;
**G-P06-CLOSE-01** full closure (PR+E+Z pre-close + pack verify); admin
``GET .../cortex/reasoning/certification-pack``;
``verify_gp06_close01_tcre_cert_pack_closure_static``,
``verify_gp06_rcpk01_reasoning_cert_pack_admin_openapi_path_matrix_static``
(``reasoning-verification-harness-spec.md`` §Gate catalog; **FF-P06-5**).
"""

from vector.domains.cortex.reasoning.anti_goals import (
    PHASE06_ANTI_GOALS_RUNTIME_SCHEMA_VERSION,
    ReasoningCognitionLeakageError,
    list_reasoning_forbidden_cognition_key_violations,
    list_reasoning_package_banned_import_violations,
    validate_reasoning_canonical_json_mapping_no_cognition_leakage,
    verify_gp06_anti01_reasoning_package_static,
    verify_gp06_json_cognition_keys_static,
)
from vector.domains.cortex.reasoning.causal_ambiguity_propagation import (
    CONFLICT_RESOLUTION_AMBIGUITY_PROPAGATION_SECTION_REF_V1,
    PHASE06_CAUSAL_AMBIGUITY_PROPAGATION_RUNTIME_SCHEMA_VERSION,
    TCRE_AMBIGUITY_REGISTRY_VERSION,
    CausalAmbiguityPropagationError,
    normalize_ambiguity_corpus_token_to_registry_id_v1,
    validate_amb_s1_no_false_certainty_coercion_v1,
    validate_ambiguity_class_id_causal_registry_v1,
    validate_causal_ambiguity_propagation_bundle_v1,
    verify_gp06_amb01_registry_literal_oracle_static,
    verify_gp06_amb02_legacy_alias_normalization_static,
    verify_gp06_amb03_unknown_corpus_token_rejected_static,
    verify_gp06_amb04_amb_s1_rejects_coercion_flags_static,
    verify_gp06_amb05_bundle_happy_path_static,
)
from vector.domains.cortex.reasoning.causal_drift_proofs import (
    CAUSAL_BREAKPOINT_DETECTION_SPEC_REF_V1,
    PHASE06_CAUSAL_DRIFT_PROOFS_RUNTIME_SCHEMA_VERSION,
    CausalDriftProofsError,
    canonical_breakpoint_id_body_v1,
    hash_breakpoint_id_v1,
    sort_breakpoint_index_rows_v1,
    validate_breakpoint_index_sorted_v1,
    validate_drift_degradation_receipt_links_breakpoints_v1,
    verify_gp06_cdp01_breakpoint_id_body_key_oracle_static,
    verify_gp06_cdp02_breakpoint_index_sort_stable_static,
    verify_gp06_cdp03_drift_receipt_requires_sorted_cd_static,
    verify_gp06_cdp04_breakpoint_id_roundtrip_static,
    verify_gp06_cdp05_policy_digest_shape_enforced_static,
)
from vector.domains.cortex.reasoning.causal_graph_ownership_continuity import (
    PHASE06_CAUSAL_GRAPH_OWNERSHIP_CONTINUITY_RUNTIME_SCHEMA_VERSION,
    CausalGraphOwnershipContinuityError,
    tcre_edge_cites_concrete_coordination_edge_ids_v1,
    validate_tcre_causal_edge_v1_reconstruction_substrate_with_ownership_v1,
    validate_tcre_causal_graph_ownership_continuity_v1,
    verify_gp06_own01_concrete_ids_require_authoritative_org_support_static,
    verify_gp06_own02_sentinel_path_skips_org_link_support_static,
    verify_gp06_own03_non_authoritative_org_support_rejected_static,
    verify_gp06_own04_substrate_plus_ownership_combined_entry_static,
)
from vector.domains.cortex.reasoning.causal_interval_closure import (
    PHASE06_CAUSAL_INTERVAL_CLOSURE_RUNTIME_SCHEMA_VERSION,
    CausalIntervalClosureError,
    canonical_sorted_tcre_causal_edge_ids_v1,
    validate_causal_influence_half_open_chain_v1,
    verify_gp06_cic01_default_policy_caps_static,
    verify_gp06_cic02_half_open_closure_oracle_static,
    verify_gp06_cic03_hop_cap_exceeded_static,
)
from vector.domains.cortex.reasoning.causal_propagation_policy import (
    PHASE06_CAUSAL_PROPAGATION_POLICY_RUNTIME_SCHEMA_VERSION,
    PROPAGATION_RULE_TABLE_V1_KEY,
    CausalPropagationPolicyError,
    max_underlying_coordination_edges_for_tcre_kind_v1,
    validate_merge_rules_coordination_edges_v1,
    validate_propagation_rule_table_v1_when_present,
    validate_tcre_edge_v1_stub_with_propagation_policy_v1,
    validate_underlying_coordination_edge_ids_propagation_v1,
    verify_gp06_edp01_default_pack_merge_rules_static,
    verify_gp06_edp02_merge_cap_multi_id_oracle_static,
    verify_gp06_edp03_default_stub_conflict_with_multi_id_resolved_static,
)
from vector.domains.cortex.reasoning.causal_reconstruction_substrate import (
    COORDINATION_EDGE_KIND_TO_TCRE_PRIMARY_V1,
    PHASE06_CAUSAL_RECONSTRUCTION_SUBSTRATE_RUNTIME_SCHEMA_VERSION,
    TCRE_CAUSAL_EDGE_REGISTRY_VERSION,
    TCRE_WEAK_COORDINATION_DERIVED_KINDS_V1,
    CausalReconstructionSubstrateError,
    primary_tcre_kind_for_coordination_edge_kind_v1,
    validate_cross_system_tcre_support_not_weak_only_v1,
    validate_tcre_causal_edge_v1_reconstruction_substrate,
    validate_tcre_payload_excludes_coordination_edge_shape_v1,
    verify_gp06_crs01_coordination_to_tcre_primary_map_static,
    verify_gp06_crs02_reconstruction_requires_confidence_static,
    verify_gp06_crs03_cross_system_weak_only_guard_static,
    verify_gp06_crs04_option_a_rejects_coordination_edge_kind_key_static,
)
from vector.domains.cortex.reasoning.chronology_degradation_propagation import (
    CANONICAL_DEGRADATION_CODES,
    CD_CHRON,
    CD_COMMIT,
    CD_CONT,
    CD_NEG,
    CD_REPLAY,
    CHRONOLOGY_LEGALITY_CLASSES_EMITTING_CD_CHRON,
    PHASE06_CHRONOLOGY_DEGRADATION_RUNTIME_SCHEMA_VERSION,
    RULE_ID_CD_CHRON_FROM_CHRONOLOGY_V1,
    ChronologyDegradationPropagationError,
    degradation_coarse_tag_v1,
    degradation_receipt_entry_v1,
    degradation_severity_rank_v1,
    effective_max_causal_hops_v1,
    list_cd_chron_from_chronology_legality_v1,
    normalize_degradation_corpus_token_v1,
    normalize_expected_degradation_classes_corpus_v1,
    sort_cd_codes_deg_mon_1_display_v1,
    sort_degradation_receipt_entries_v1,
    validate_degradation_multiset_monotonic_extension_v1,
    validate_policy_caps_g_p06_pol01_v1,
    verify_gp06_deg01_corpus_alias_registry_static,
    verify_gp06_deg02_severity_sort_oracle_static,
    verify_gp06_deg03_default_policy_caps_static,
)
from vector.domains.cortex.reasoning.chronology_legality import (
    CHRONOLOGY_LEGALITY_CLASSES,
    PHASE06_CHRONOLOGY_LEGALITY_RUNTIME_SCHEMA_VERSION,
    TCRE_REASONING_POLICY_PACK_V1_DEFAULT_DIGEST,
    ChronologyLegalityError,
    chronology_projection_matched_row_canonical_index,
    default_reasoning_policy_pack_path,
    find_chronology_skew_projection_row,
    load_default_reasoning_policy_pack,
    project_chronology_legality_class_v1,
    should_emit_cd_chron_from_policy,
    validate_chron_forb1,
    verify_default_policy_pack_digest,
    verify_gp06_chron01_default_policy_rows_static,
    verify_gp06_chron02_projection_closure_static,
)
from vector.domains.cortex.reasoning.commitment_derived_causality import (
    PHASE06_COMMITMENT_DERIVED_CAUSALITY_RUNTIME_SCHEMA_VERSION,
    TCRE_COMMITMENT_TRANSITION_DERIVATION_RULE_PREFIX_V1,
    TCRE_COMMITMENT_TRANSITION_KIND,
    CommitmentDerivedCausalityError,
    lineage_includes_commitment_contract_hop_v1,
    lineage_includes_raw_record_hop_v1,
    underlying_coordination_edge_ids_sentinel_only_v1,
    validate_tcre_causal_edge_v1_reconstruction_substrate_commitment_transition_v1,
    validate_tcre_commitment_transition_causality_v1,
    validate_tcre_commitment_transition_derivation_rule_v1,
    validate_tcre_commitment_transition_sentinel_lineage_v1,
    verify_gp06_cmt01_sentinel_requires_raw_and_commitment_hop_static,
    verify_gp06_cmt02_concrete_coordination_skips_extra_commitment_hop_static,
    verify_gp06_cmt03_bad_derivation_rule_prefix_rejected_static,
    verify_gp06_cmt04_wrong_kind_rejected_static,
    verify_gp06_cmt05_substrate_plus_commitment_law_static,
)
from vector.domains.cortex.reasoning.cross_system_time_reconciliation import (
    CONSTITUTIONAL_CROSS_SYSTEM_CAUSAL_MIN_RANK_V1,
    CONTINUITY_BRIDGE_STRENGTH_TO_RANK_V1,
    CONTINUITY_BRIDGE_STRENGTHS_V1,
    PHASE06_CROSS_SYSTEM_TIME_RECONCILIATION_RUNTIME_SCHEMA_VERSION,
    CrossSystemTimeReconciliationError,
    continuity_bridge_strength_rank_v1,
    continuity_bridge_strictly_stronger_v1,
    cross_system_causal_effective_min_rank_v1,
    skew_flag_tuple_from_reasoning_snapshot_v1,
    validate_chronology_allows_strict_temporal_order_claim_v1,
    validate_cross_system_causal_continuity_requirements_v1,
    verify_gp06_xst01_rank_table_oracle_static,
    verify_gp06_xst02_default_policy_min_rank_static,
    verify_gp06_xst03_cross_caus_rank4_derivation_gate_static,
)
from vector.domains.cortex.reasoning.deterministic_causal_chain import (
    PHASE06_DETERMINISTIC_CAUSAL_CHAIN_RUNTIME_SCHEMA_VERSION,
    DeterministicCausalChainError,
    causal_chain_id_canonical_body_v1,
    hash_causal_chain_id_v1,
    validate_tcre_policy_bundle_digest_shape_v1,
    verify_causal_chain_id_v1,
    verify_gp06_dcc01_causal_chain_id_permutation_invariant_static,
    verify_gp06_dcc02_policy_digest_participates_static,
    verify_gp06_dcc03_canonical_body_sorted_keys_static,
)
from vector.domains.cortex.reasoning.execution_causality_constraints import (
    CAUSAL_LEGALITY_CLASSES,
    CAUSAL_LEGALITY_ENUM_VERSION_V1,
    EXECUTION_CAUSALITY_RUNTIME_SCHEMA_VERSION,
    NO_COORDINATION_EDGE_SENTINEL,
    TCRE_CAUSAL_EDGE_KINDS,
    ExecutionCausalityConstraintError,
    coordination_edge_kind_is_known,
    list_lrel_forbidden_keys_on_mapping,
    validate_causal_legality_class,
    validate_parent_artifact_ids_sorted_unique,
    validate_tcre_edge_v1_stub,
    verify_gp06_clc01_literal_table_oracle_static,
    verify_gp06_clc02_tcre_stub_accepts_each_legal_literal_static,
    verify_gp06_clc03_tcre_stub_rejects_unknown_causal_legality_static,
    verify_gp06_clc04_tcre_stub_omits_causal_legality_class_static,
    verify_gp06_ecc01_causal_legality_enum_static,
    verify_gp06_ecc02_parent_artifact_ids_static,
    verify_gp06_ecc03_tcre_edge_shape_static,
)
from vector.domains.cortex.reasoning.interval_continuity import (
    PHASE06_INTERVAL_CONTINUITY_RUNTIME_SCHEMA_VERSION,
    REASONING_CHRONOLOGY_RECEIPT_TYPE,
    IntervalContinuityError,
    reasoning_chronology_receipt_body_v1,
    validate_chronology_snapshot_read_only_replay_safe_ordering_v1,
    validate_half_open_interval_chain_continuity_v1,
    validate_interval_graph_and_emit_chronology_receipt_v1,
    validate_reasoning_interval_slice_half_open_v1,
    verify_gp06_int01_half_open_chain_continuity_static,
    verify_gp06_int02_chronology_receipt_projection_static,
)
from vector.domains.cortex.reasoning.negative_signal_causality import (
    NEGATIVE_SIGNAL_KINDS_SILENCE_CAUSALITY_LAWFUL_V1,
    PHASE06_NEGATIVE_SIGNAL_CAUSALITY_RUNTIME_SCHEMA_VERSION,
    TCRE_NEGATIVE_SIGNAL_DERIVATION_RULE_PREFIX_V1,
    TCRE_NEGATIVE_SIGNAL_KIND,
    NegativeSignalCausalityError,
    lineage_includes_negative_signal_contract_hop_v1,
    lineage_includes_raw_record_hop_negative_v1,
    resolve_negative_signal_kind_v1,
    underlying_coordination_edge_ids_sentinel_only_negative_v1,
    validate_tcre_causal_edge_v1_reconstruction_substrate_negative_signal_v1,
    validate_tcre_negative_signal_causality_v1,
    validate_tcre_negative_signal_derivation_rule_v1,
    validate_tcre_negative_signal_kind_silence_law_v1,
    validate_tcre_negative_signal_sentinel_lineage_v1,
    verify_gp06_neg01_sentinel_requires_raw_and_signal_hop_static,
    verify_gp06_neg02_concrete_coordination_skips_extra_signal_hop_static,
    verify_gp06_neg03_bad_derivation_rule_prefix_rejected_static,
    verify_gp06_neg04_unlawful_negative_signal_kind_rejected_static,
    verify_gp06_neg05_substrate_plus_negative_signal_law_static,
)
from vector.domains.cortex.reasoning.normative import PHASE06_PROGRAM_FREEZE_VERSION
from vector.domains.cortex.reasoning.organizational_continuity_reasoning import (
    AMB_BRIDGE_WEAK,
    KNOWN_AMBIGUITY_CLASS_IDS,
    LINK_AUTHORITY_AUTHORITATIVE,
    PHASE06_ORG_CONTINUITY_RUNTIME_SCHEMA_VERSION,
    REPLAY_POSTURE_REPLAY_CONFLICTED,
    OrganizationalContinuityReasoningError,
    validate_ambiguity_class_id_registered,
    validate_authoritative_link_gates_for_tcre_support,
    validate_candidate_or_hint_not_sole_without_bridge_weak,
    validate_evidence_lineage_has_raw_or_ledger_hop,
    validate_replay_conflicted_walk_propagates,
    verify_gp06_cont01_authoritative_link_gate_static,
    verify_gp06_cont02_candidate_hint_sole_static,
    verify_gp06_cont03_evidence_lineage_substrate_static,
    verify_gp06_cont04_replay_conflicted_propagation_static,
)
from vector.domains.cortex.reasoning.proof_bundle_composition import (
    PHASE06_PROOF_BUNDLE_COMPOSITION_RUNTIME_SCHEMA_VERSION,
    PROOF_BUNDLE_COMPOSITION_SPEC_REF_V1,
    ProofBundleCompositionError,
    build_proof_bundle_inner_digest_body_v1,
    hash_proof_bundle_inner_digest_v1,
    validate_proof_bundle_equivalence_receipt_set_v1,
    verify_gp06_pbc01_inner_body_sorted_pairs_oracle_static,
    verify_gp06_pbc02_equivalence_receipt_always_required_static,
    verify_gp06_pbc03_chronology_required_when_participates_static,
    verify_gp06_pbc04_inner_hash_permutation_invariant_static,
    verify_gp06_pbc05_full_minimal_bundle_validates_static,
)
from vector.domains.cortex.reasoning.reasoning_certification_pack import (
    PHASE06_REASONING_CERTIFICATION_PACK_RUNTIME_SCHEMA_VERSION,
    REASONING_CERTIFICATION_PACK_ADMIN_OPENAPI_PATHS_V1,
    TCRE_CERT_PACK_FORMAT_LITERAL_V1,
    TCRE_CERT_PACK_MANIFEST_FORMAT_KEY_V1,
    TCRE_CERT_PACK_REQUIRED_ROOT_FILES_V1,
    build_reasoning_certification_pack_snapshot_v1,
    build_tcre_cert_pack_v1,
    verify_gp06_close01_tcre_cert_pack_closure_static,
    verify_gp06_close01_tcre_cert_pack_shape_reference_static,
    verify_gp06_rcpk01_reasoning_cert_pack_admin_openapi_path_matrix_static,
    verify_tcre_cert_pack_v1,
)
from vector.domains.cortex.reasoning.reasoning_ci_enforcement_architecture import (
    PHASE06_REASONING_CI_ENFORCEMENT_ARCHITECTURE_RUNTIME_SCHEMA_VERSION,
    REASONING_CI_ENFORCEMENT_ARCH_HARNESS_SPEC_REF_V1,
    REASONING_CI_ENFORCEMENT_ARCH_PHASE05_REF_V1,
    REASONING_GP06_CI_FULL_STATIC_STAGES_V1,
    REASONING_GP06_CI_INVARIANT_PARALLEL_STAGES_V1,
    REASONING_GP06_CI_PR_BLOCKING_STAGES_V1,
    list_reasoning_gp06_ci_stage_letters_ordered_v1,
    reasoning_gp06_ci_full_stage_row_map_v1,
    run_reasoning_gp06_ci_full_az_topology_with_meta_v1,
    run_reasoning_gp06_ci_full_wired_stages_with_meta_v1,
    run_reasoning_gp06_ci_pr_blocking_bundle_v1,
    verify_gp06_cia01_full_stage_row_partition_covers_doctrine_static,
    verify_gp06_cia02_pr_blocking_stages_match_constant_and_underlying_static,
    verify_gp06_cia03_severity_defaults_hard_fail_all_doctrine_static,
    verify_gp06_cia04_wired_runner_keys_equal_doctrine_static,
    verify_gp06_cia05_full_az_topology_including_empty_rows_passes_static,
    verify_gp06_cia06_close_gate_is_last_in_stage_z_static,
    verify_gp06_cia07_phase05_doc_anchor_present_static,
    verify_gp06_cia08_ci_invariant_literal_frozen_static,
)
from vector.domains.cortex.reasoning.reasoning_control_plane import (
    PHASE06_REASONING_CONTROL_PLANE_RUNTIME_SCHEMA_VERSION,
    REASONING_ADMIN_CONTROL_PLANE_SPEC_REF_V1,
    REASONING_CONTROL_PLANE_ADMIN_OPENAPI_PATHS_V1,
    REASONING_CONTROL_PLANE_CONTRACT_V1,
    REASONING_CONTROL_PLANE_RBAC_SUBSTRATE_LITERAL_V1,
    REASONING_CONTROL_PLANE_SURFACE_VERSION_V1,
    REASONING_CONTROL_PLANE_SURFACES_V1,
    REASONING_DANGEROUS_ACTION_SAFETY_MODEL_REF_V1,
    ReasoningControlPlaneSurfaceV1,
    build_reasoning_control_plane_catalog_v1,
    list_reasoning_control_plane_surface_ids_v1,
    verify_gp06_rcp01_surface_catalog_sorted_unique_static,
    verify_gp06_rcp02_surfaces_match_admin_spec_table_static,
    verify_gp06_rcp03_doctrine_refs_frozen_static,
    verify_gp06_rcp04_build_catalog_contract_shape_static,
    verify_gp06_rcp05_admin_openapi_path_matrix_static,
    verify_gp06_rcp06_rbac_substrate_literal_frozen_static,
)
from vector.domains.cortex.reasoning.reasoning_golden_thread_binding import (
    GOLDEN_THREAD_REPLAY_CORPUS_SPEC_REF_V1,
    PHASE06_REASONING_GOLDEN_THREAD_BINDING_RUNTIME_SCHEMA_VERSION,
    REASONING_GOLDEN_THREAD_CORPUS_SCHEMA_VERSION_V1,
    REASONING_VERIFICATION_HARNESS_GOLDEN_VECTORS_REF_V1,
    ReasoningGoldenThreadCorpusBindingError,
    bind_reasoning_golden_corpus_at_root_v1,
    hash_reasoning_corpus_manifest_digest_v1,
    load_reasoning_corpus_case_v1,
    load_reasoning_corpus_manifest_v1,
    reasoning_golden_vectors_v1_root,
    validate_reasoning_corpus_case_header_v1,
    validate_reasoning_corpus_manifest_v1,
    verify_gp06_gtc01_default_manifest_shape_static,
    verify_gp06_gtc02_case_ambiguity_binding_static,
    verify_gp06_gtc03_case_degradation_cd_binding_static,
    verify_gp06_gtc04_optional_tcre_chains_shape_static,
    verify_gp06_gtc05_full_bind_roundtrip_static,
)
from vector.domains.cortex.reasoning.reasoning_provenance_law import (
    PHASE06_REASONING_PROVENANCE_LAW_RUNTIME_SCHEMA_VERSION,
    REASONING_PROVENANCE_LAW_SPEC_REF_V1,
    REASONING_REPLAY_POSTURE_LITERALS_V1,
    ReasoningProvenanceLawError,
    reasoning_provenance_minimal_valid_fixture_v1,
    validate_reasoning_artifact_provenance_envelope_v1,
    verify_gp06_rpl01_replay_posture_literal_oracle_static,
    verify_gp06_rpl02_minimal_envelope_happy_path_static,
    verify_gp06_rpl03_missing_lineage_rejected_static,
    verify_gp06_rpl04_cross_system_requires_org_link_static,
    verify_gp06_rpl05_deprecated_degradation_semantics_rejected_static,
)
from vector.domains.cortex.reasoning.reasoning_readiness_economics import (
    REASONING_ECONOMICS_THRESHOLD_TABLE_VERSION_V1,
    REASONING_READINESS_ECONOMICS_ADMIN_OPENAPI_PATHS_V1,
    REASONING_READINESS_ECONOMICS_CONTRACT_V1,
    REASONING_READINESS_ECONOMICS_SCHEMA_VERSION,
    build_reasoning_readiness_economics_receipt_v1,
    compute_reasoning_economics_receipt_hash_v1,
    verify_gp06_rreco01_readiness_economics_clean_profile_static,
    verify_gp06_rreco02_readiness_economics_hostile_profile_static,
    verify_gp06_rreco03_admin_openapi_path_matrix_static,
)
from vector.domains.cortex.reasoning.reasoning_receipts_proof_artifacts import (
    PHASE06_REASONING_RECEIPTS_PROOF_ARTIFACTS_RUNTIME_SCHEMA_VERSION,
    REASONING_AMBIGUITY_RECEIPT_TYPE,
    REASONING_CANON_VERSION_V1,
    REASONING_CAUSAL_RECEIPT_TYPE,
    REASONING_EQUIVALENCE_RECEIPT_TYPE,
    REASONING_RECEIPT_TYPES_V1,
    ReasoningReceiptsProofArtifactsError,
    hash_reasoning_canonical_json_sha256_v1,
    reasoning_ambiguity_receipt_body_v1,
    reasoning_causal_receipt_body_v1,
    reasoning_equivalence_receipt_body_v1,
    validate_reasoning_receipt_type_literal_v1,
    verify_gp06_rra01_receipt_type_catalog_oracle_static,
    verify_gp06_rra02_canonical_hash_stable_under_key_order_static,
    verify_gp06_rra03_causal_receipt_sorted_ids_enforced_static,
    verify_gp06_rra04_ambiguity_receipt_happy_path_static,
    verify_gp06_rra05_equivalence_receipt_happy_path_static,
)
from vector.domains.cortex.reasoning.reasoning_runtime_legality_matrix import (
    CHRONOLOGY_REPLAY_LEGALITY_STATE_MACHINE_REF_V1,
    PHASE05_RUNTIME_LEGALITY_MATRIX_REF_V1,
    PHASE06_REASONING_RUNTIME_LEGALITY_MATRIX_RUNTIME_SCHEMA_VERSION,
    REASONING_RUNTIME_FORBIDDEN_DEPLOYMENTS_V1,
    REASONING_RUNTIME_LEGALITY_DANGEROUS_ACTION_REF_V1,
    REASONING_RUNTIME_LEGALITY_MATRIX_ADMIN_OPENAPI_PATHS_V1,
    REASONING_RUNTIME_LEGALITY_MATRIX_CONTRACT_V1,
    REASONING_RUNTIME_LEGALITY_MATRIX_SPEC_REF_V1,
    REASONING_RUNTIME_LEGALITY_MATRIX_SURFACE_VERSION_V1,
    REASONING_RUNTIME_LEGALITY_PREDICATES_V1,
    REASONING_VERIFICATION_WAIVERS_YAML_FUTURE_PATH_V1,
    ReasoningRuntimeForbiddenDeploymentV1,
    ReasoningRuntimeLegalityPredicateV1,
    build_reasoning_runtime_legality_matrix_catalog_v1,
    list_reasoning_runtime_legality_predicate_ids_v1,
    verify_gp06_rlm01_predicate_catalog_five_sorted_unique_static,
    verify_gp06_rlm02_r_leg02_anti01_ci_green_static,
    verify_gp06_rlm03_cross_doc_anchors_frozen_static,
    verify_gp06_rlm04_forbidden_deployments_shape_static,
    verify_gp06_rlm05_waiver_yaml_future_path_literal_static,
    verify_gp06_rlm06_build_catalog_contract_shape_static,
    verify_gp06_rlm07_admin_openapi_path_matrix_static,
)
from vector.domains.cortex.reasoning.reasoning_tenant_verification_slice import (
    ORG_GRAPH_REASONING_VERIFICATION_SLICE_SCHEMA_VERSION,
    REASONING_TENANT_VERIFICATION_SLICE_ADMIN_OPENAPI_PATHS_V1,
    VECTOR_REASONING_TENANT_VERIFICATION_SLICE_ENV,
    build_org_graph_reasoning_verification_slice_v1,
    compute_reasoning_verification_slice_hash_v1,
    list_fs_rtv01_slice_float_violations_v1,
    reasoning_tenant_verification_slice_enabled_v1,
    validate_org_graph_reasoning_verification_slice_v1,
    verify_gp06_rtvs01_org_graph_reasoning_slice_golden_static,
    verify_gp06_rtvs02_admin_openapi_path_matrix_static,
)
from vector.domains.cortex.reasoning.reasoning_verification_harness import (
    OCTS_CERT_PACK_REQUIRED_ROOT_FILES_V1,
    PHASE06_REASONING_VERIFICATION_HARNESS_RUNTIME_SCHEMA_VERSION,
    REASONING_GP06_CORRUPTION_BUNDLES_V1,
    REASONING_GP06_DOCTRINE_GATE_IDS_V1,
    REASONING_VERIFICATION_HARNESS_CATALOG_VERSION_V1,
    REASONING_VERIFICATION_HARNESS_SPEC_REF_V1,
    REASONING_VERIFICATION_MODE_ENV,
    default_severity_for_reasoning_gate_v1,
    list_reasoning_gp06_doctrine_gate_ids_v1,
    list_reasoning_gp06_wired_verification_runners_v1,
    reasoning_gp06_gate_stage_v1,
    run_reasoning_gp06_pr_blocking_static_stages_v1,
    run_reasoning_gp06_wired_verification_stages_v1,
    verify_gp06_rvh01_harness_catalog_covers_spec_gate_table_static,
    verify_gp06_rvh02_pr_blocking_bundle_passes_static,
    verify_gp06_rvh03_full_stage_az_includes_close_static,
    verify_reasoning_gp06_corruption_bundles_subset_static,
    verify_reasoning_gp06_gate_catalog_unique_ids_static,
    verify_reasoning_gp06_wired_runner_gate_ids_match_static,
)
from vector.domains.cortex.reasoning.replay_chronology import (
    PHASE06_REPLAY_CHRONOLOGY_RUNTIME_SCHEMA_VERSION,
    REASONING_REPLAY_PERMUTATION_PROFILE_ID,
    REASONING_REPLAY_RECEIPT_TYPE,
    REPLAY_PINNED_WALK_NO_INPUT_SENTINEL,
    ReplayChronologyError,
    canonical_reasoning_replay_permutation_v1_json,
    hash_pinned_replay_chronology_tuple_v1,
    reasoning_replay_receipt_body_v1,
    validate_chronology_snapshot_matches_pinned_replay_tuple_v1,
    validate_pinned_replay_chronology_tuple_v1,
    validate_reasoning_replay_permutation_v1_json,
    verify_gp06_rep01_permutation_canonical_static,
    verify_gp06_rep02_pinned_tuple_hash_static,
)
from vector.domains.cortex.reasoning.replay_equivalence_proofs import (
    GP06_REPLAY_01_GATE_ID_V1,
    PHASE06_REPLAY_EQUIVALENCE_PROOFS_RUNTIME_SCHEMA_VERSION,
    REPLAY_EQUIVALENCE_SPEC_SECTION_REF_V1,
    ReplayEquivalenceProofsError,
    compare_gp06_replay_01_double_run_v1,
    normalize_gp06_replay_01_comparison_vector_v1,
    validate_gp06_replay_01_equivalence_claim_scope_v1,
    verify_gp06_req01_replay_01_gate_id_oracle_static,
    verify_gp06_req02_permutation_profile_id_literal_static,
    verify_gp06_req03_minimal_bundle_double_run_match_static,
    verify_gp06_req04_chronology_digest_required_when_participates_static,
    verify_gp06_req05_double_run_mismatch_raises_static,
    verify_gp06_req06_causal_only_insufficient_when_receipts_static,
)
from vector.domains.cortex.reasoning.replay_safe_reasoning_posture import (
    PHASE06_REPLAY_SAFE_REASONING_POSTURE_RUNTIME_SCHEMA_VERSION,
    ReplaySafeReasoningPostureError,
    validate_replay_safe_reasoning_posture_from_mapping_v1,
    validate_replay_safe_reasoning_posture_v1,
    verify_gp06_rsp01_replay_safe_posture_happy_path_static,
    verify_gp06_rsp02_policy_digest_shape_rejected_static,
    verify_gp06_rsp03_permutation_profile_id_enforced_static,
    verify_gp06_rsp04_pinned_tuple_hash_stable_under_posture_static,
)
from vector.domains.cortex.reasoning.temporal_anchor_resolution import (
    PHASE06_TEMPORAL_ANCHOR_RESOLUTION_RUNTIME_SCHEMA_VERSION,
    REASONING_TEMPORAL_ANCHOR_RESOLUTION_RECEIPT_TYPE,
    TEMPORAL_ANCHOR_RESOLUTION_ORDER_V1,
    TemporalAnchorResolutionError,
    declare_replay_safe_ordering_v1,
    hash_reasoning_receipt_canonical_v1,
    normalize_observed_at_iso,
    reject_median_time_resolution_heuristic,
    resolve_temporal_anchor_chain_v1,
    sort_anchors_temporal_anchor_resolution_order_v1,
    temporal_anchor_resolution_sort_key_v1,
    validate_temporal_anchor_resolution_inputs_v1,
    verify_gp06_tar01_resolution_order_literal_static,
    verify_gp06_tar02_declare_replay_safe_ordering_static,
)
from vector.domains.cortex.reasoning.temporal_conflict_resolution import (
    PHASE06_TEMPORAL_CONFLICT_RUNTIME_SCHEMA_VERSION,
    TEMPORAL_CONFLICT_CLASS_IDS,
    TemporalConflictResolutionError,
    chronology_projection_snapshot_from_temporal_conflict_v1,
    temporal_conflict_precedence_rank_v1,
    validate_chronology_strict_requires_resolved_pairs_v1,
    validate_export_vs_observed_conflict_flags_v1,
    validate_temporal_active_conflict_classes_v1,
    validate_temporal_conflict_no_history_rewrite_v1,
    verify_gp06_tcr01_precedence_oracle_static,
    verify_gp06_tcr02_chronology_strict_pairwise_static,
    verify_gp06_tcr03_conflict_class_registry_static,
)
from vector.domains.cortex.reasoning.temporal_reasoning import (
    PHASE06_TEMPORAL_REASONING_RUNTIME_SCHEMA_VERSION,
    REPLAY_SAFE_ORDERING_LITERALS,
    TemporalReasoningInvariantError,
    validate_cross_source_temporal_reference_contract,
    validate_half_open_interval_iso,
    validate_late_arrival_append_only,
    validate_no_replay_safe_ordering_mutation_claim,
    validate_reasoning_interval_has_anchor_or_raw_lineage,
    validate_replay_safe_ordering_read_only_value,
    verify_gp06_tr01_interval_lineage_static,
    verify_gp06_tr02_late_arrival_append_static,
    verify_gp06_tr03_cross_source_reference_static,
    verify_gp06_tr04_half_open_interval_static,
)
from vector.domains.cortex.reasoning.unverifiable_degraded_causality import (
    CAUSAL_DEGRADATION_SPEC_MONOTONICITY_REF_V1,
    CAUSAL_LEGALITY_UNVERIFIABLE_V1,
    PHASE06_UNVERIFIABLE_DEGRADED_CAUSALITY_RUNTIME_SCHEMA_VERSION,
    UnverifiableDegradedCausalityError,
    normalize_cd_corpus_tokens_sorted_unique_v1,
    validate_cd_multiset_monotonic_extension_degraded_v1,
    validate_degradation_receipt_entries_sorted_v1,
    validate_unverifiable_causality_requires_cd_codes_v1,
    verify_gp06_udc01_canonical_cd_literal_oracle_static,
    verify_gp06_udc02_severity_rank_table_oracle_static,
    verify_gp06_udc03_monotonic_regression_rejected_static,
    verify_gp06_udc04_unverifiable_requires_cd_static,
    verify_gp06_udc05_degradation_receipt_sort_stable_static,
)

__all__ = (
    "AMB_BRIDGE_WEAK",
    "CAUSAL_BREAKPOINT_DETECTION_SPEC_REF_V1",
    "CAUSAL_DEGRADATION_SPEC_MONOTONICITY_REF_V1",
    "CAUSAL_LEGALITY_CLASSES",
    "CAUSAL_LEGALITY_ENUM_VERSION_V1",
    "CAUSAL_LEGALITY_UNVERIFIABLE_V1",
    "CANONICAL_DEGRADATION_CODES",
    "CD_CHRON",
    "CD_COMMIT",
    "CD_CONT",
    "CD_NEG",
    "CD_REPLAY",
    "CHRONOLOGY_LEGALITY_CLASSES",
    "CHRONOLOGY_LEGALITY_CLASSES_EMITTING_CD_CHRON",
    "CONFLICT_RESOLUTION_AMBIGUITY_PROPAGATION_SECTION_REF_V1",
    "CONSTITUTIONAL_CROSS_SYSTEM_CAUSAL_MIN_RANK_V1",
    "CONTINUITY_BRIDGE_STRENGTHS_V1",
    "CONTINUITY_BRIDGE_STRENGTH_TO_RANK_V1",
    "COORDINATION_EDGE_KIND_TO_TCRE_PRIMARY_V1",
    "EXECUTION_CAUSALITY_RUNTIME_SCHEMA_VERSION",
    "GP06_REPLAY_01_GATE_ID_V1",
    "GOLDEN_THREAD_REPLAY_CORPUS_SPEC_REF_V1",
    "KNOWN_AMBIGUITY_CLASS_IDS",
    "LINK_AUTHORITY_AUTHORITATIVE",
    "NEGATIVE_SIGNAL_KINDS_SILENCE_CAUSALITY_LAWFUL_V1",
    "NO_COORDINATION_EDGE_SENTINEL",
    "ORG_GRAPH_REASONING_VERIFICATION_SLICE_SCHEMA_VERSION",
    "OCTS_CERT_PACK_REQUIRED_ROOT_FILES_V1",
    "PHASE06_ANTI_GOALS_RUNTIME_SCHEMA_VERSION",
    "PHASE06_CAUSAL_AMBIGUITY_PROPAGATION_RUNTIME_SCHEMA_VERSION",
    "PHASE06_CAUSAL_DRIFT_PROOFS_RUNTIME_SCHEMA_VERSION",
    "PHASE06_CAUSAL_PROPAGATION_POLICY_RUNTIME_SCHEMA_VERSION",
    "PHASE06_CAUSAL_GRAPH_OWNERSHIP_CONTINUITY_RUNTIME_SCHEMA_VERSION",
    "PHASE06_CAUSAL_INTERVAL_CLOSURE_RUNTIME_SCHEMA_VERSION",
    "PHASE06_CAUSAL_RECONSTRUCTION_SUBSTRATE_RUNTIME_SCHEMA_VERSION",
    "PHASE06_CHRONOLOGY_DEGRADATION_RUNTIME_SCHEMA_VERSION",
    "PHASE06_CHRONOLOGY_LEGALITY_RUNTIME_SCHEMA_VERSION",
    "PHASE06_COMMITMENT_DERIVED_CAUSALITY_RUNTIME_SCHEMA_VERSION",
    "PHASE06_CROSS_SYSTEM_TIME_RECONCILIATION_RUNTIME_SCHEMA_VERSION",
    "PHASE06_DETERMINISTIC_CAUSAL_CHAIN_RUNTIME_SCHEMA_VERSION",
    "PHASE06_INTERVAL_CONTINUITY_RUNTIME_SCHEMA_VERSION",
    "PHASE06_NEGATIVE_SIGNAL_CAUSALITY_RUNTIME_SCHEMA_VERSION",
    "PHASE06_ORG_CONTINUITY_RUNTIME_SCHEMA_VERSION",
    "PHASE06_PROGRAM_FREEZE_VERSION",
    "PHASE06_PROOF_BUNDLE_COMPOSITION_RUNTIME_SCHEMA_VERSION",
    "PHASE06_REASONING_PROVENANCE_LAW_RUNTIME_SCHEMA_VERSION",
    "PHASE06_REASONING_RECEIPTS_PROOF_ARTIFACTS_RUNTIME_SCHEMA_VERSION",
    "PHASE06_REASONING_VERIFICATION_HARNESS_RUNTIME_SCHEMA_VERSION",
    "PHASE06_REASONING_CERTIFICATION_PACK_RUNTIME_SCHEMA_VERSION",
    "PHASE06_REASONING_CI_ENFORCEMENT_ARCHITECTURE_RUNTIME_SCHEMA_VERSION",
    "PHASE06_REASONING_CONTROL_PLANE_RUNTIME_SCHEMA_VERSION",
    "PHASE06_REASONING_RUNTIME_LEGALITY_MATRIX_RUNTIME_SCHEMA_VERSION",
    "PHASE06_REASONING_GOLDEN_THREAD_BINDING_RUNTIME_SCHEMA_VERSION",
    "PHASE06_REPLAY_CHRONOLOGY_RUNTIME_SCHEMA_VERSION",
    "PHASE06_REPLAY_EQUIVALENCE_PROOFS_RUNTIME_SCHEMA_VERSION",
    "PHASE06_REPLAY_SAFE_REASONING_POSTURE_RUNTIME_SCHEMA_VERSION",
    "PHASE06_TEMPORAL_ANCHOR_RESOLUTION_RUNTIME_SCHEMA_VERSION",
    "PHASE06_TEMPORAL_CONFLICT_RUNTIME_SCHEMA_VERSION",
    "PHASE06_TEMPORAL_REASONING_RUNTIME_SCHEMA_VERSION",
    "PHASE06_UNVERIFIABLE_DEGRADED_CAUSALITY_RUNTIME_SCHEMA_VERSION",
    "PROOF_BUNDLE_COMPOSITION_SPEC_REF_V1",
    "PROPAGATION_RULE_TABLE_V1_KEY",
    "REASONING_AMBIGUITY_RECEIPT_TYPE",
    "REASONING_CANON_VERSION_V1",
    "REASONING_CAUSAL_RECEIPT_TYPE",
    "REASONING_CERTIFICATION_PACK_ADMIN_OPENAPI_PATHS_V1",
    "REASONING_CHRONOLOGY_RECEIPT_TYPE",
    "REASONING_CI_ENFORCEMENT_ARCH_HARNESS_SPEC_REF_V1",
    "REASONING_CI_ENFORCEMENT_ARCH_PHASE05_REF_V1",
    "REASONING_ADMIN_CONTROL_PLANE_SPEC_REF_V1",
    "REASONING_EQUIVALENCE_RECEIPT_TYPE",
    "REASONING_GP06_CORRUPTION_BUNDLES_V1",
    "REASONING_GP06_CI_FULL_STATIC_STAGES_V1",
    "REASONING_GP06_CI_INVARIANT_PARALLEL_STAGES_V1",
    "REASONING_GP06_CI_PR_BLOCKING_STAGES_V1",
    "REASONING_GP06_DOCTRINE_GATE_IDS_V1",
    "REASONING_CONTROL_PLANE_ADMIN_OPENAPI_PATHS_V1",
    "REASONING_CONTROL_PLANE_CONTRACT_V1",
    "REASONING_CONTROL_PLANE_RBAC_SUBSTRATE_LITERAL_V1",
    "REASONING_CONTROL_PLANE_SURFACE_VERSION_V1",
    "REASONING_CONTROL_PLANE_SURFACES_V1",
    "REASONING_DANGEROUS_ACTION_SAFETY_MODEL_REF_V1",
    "CHRONOLOGY_REPLAY_LEGALITY_STATE_MACHINE_REF_V1",
    "PHASE05_RUNTIME_LEGALITY_MATRIX_REF_V1",
    "REASONING_RUNTIME_FORBIDDEN_DEPLOYMENTS_V1",
    "REASONING_RUNTIME_LEGALITY_MATRIX_ADMIN_OPENAPI_PATHS_V1",
    "REASONING_RUNTIME_LEGALITY_MATRIX_CONTRACT_V1",
    "REASONING_RUNTIME_LEGALITY_MATRIX_SPEC_REF_V1",
    "REASONING_RUNTIME_LEGALITY_MATRIX_SURFACE_VERSION_V1",
    "REASONING_RUNTIME_LEGALITY_PREDICATES_V1",
    "REASONING_ECONOMICS_THRESHOLD_TABLE_VERSION_V1",
    "REASONING_READINESS_ECONOMICS_ADMIN_OPENAPI_PATHS_V1",
    "REASONING_READINESS_ECONOMICS_CONTRACT_V1",
    "REASONING_READINESS_ECONOMICS_SCHEMA_VERSION",
    "REASONING_TENANT_VERIFICATION_SLICE_ADMIN_OPENAPI_PATHS_V1",
    "REASONING_RUNTIME_LEGALITY_DANGEROUS_ACTION_REF_V1",
    "REASONING_VERIFICATION_WAIVERS_YAML_FUTURE_PATH_V1",
    "REASONING_GOLDEN_THREAD_CORPUS_SCHEMA_VERSION_V1",
    "REASONING_PROVENANCE_LAW_SPEC_REF_V1",
    "REASONING_RECEIPT_TYPES_V1",
    "REASONING_REPLAY_PERMUTATION_PROFILE_ID",
    "REASONING_REPLAY_POSTURE_LITERALS_V1",
    "REASONING_REPLAY_RECEIPT_TYPE",
    "REASONING_VERIFICATION_HARNESS_CATALOG_VERSION_V1",
    "REASONING_VERIFICATION_HARNESS_SPEC_REF_V1",
    "REASONING_VERIFICATION_HARNESS_GOLDEN_VECTORS_REF_V1",
    "REASONING_VERIFICATION_MODE_ENV",
    "VECTOR_REASONING_TENANT_VERIFICATION_SLICE_ENV",
    "ReasoningControlPlaneSurfaceV1",
    "ReasoningRuntimeForbiddenDeploymentV1",
    "ReasoningRuntimeLegalityPredicateV1",
    "REASONING_TEMPORAL_ANCHOR_RESOLUTION_RECEIPT_TYPE",
    "RULE_ID_CD_CHRON_FROM_CHRONOLOGY_V1",
    "REPLAY_EQUIVALENCE_SPEC_SECTION_REF_V1",
    "REPLAY_PINNED_WALK_NO_INPUT_SENTINEL",
    "REPLAY_POSTURE_REPLAY_CONFLICTED",
    "REPLAY_SAFE_ORDERING_LITERALS",
    "TEMPORAL_ANCHOR_RESOLUTION_ORDER_V1",
    "TEMPORAL_CONFLICT_CLASS_IDS",
    "TCRE_AMBIGUITY_REGISTRY_VERSION",
    "TCRE_CAUSAL_EDGE_KINDS",
    "TCRE_CAUSAL_EDGE_REGISTRY_VERSION",
    "TCRE_CERT_PACK_FORMAT_LITERAL_V1",
    "TCRE_CERT_PACK_MANIFEST_FORMAT_KEY_V1",
    "TCRE_CERT_PACK_REQUIRED_ROOT_FILES_V1",
    "TCRE_COMMITMENT_TRANSITION_DERIVATION_RULE_PREFIX_V1",
    "TCRE_COMMITMENT_TRANSITION_KIND",
    "TCRE_NEGATIVE_SIGNAL_DERIVATION_RULE_PREFIX_V1",
    "TCRE_NEGATIVE_SIGNAL_KIND",
    "TCRE_REASONING_POLICY_PACK_V1_DEFAULT_DIGEST",
    "TCRE_WEAK_COORDINATION_DERIVED_KINDS_V1",
    "CausalAmbiguityPropagationError",
    "CausalDriftProofsError",
    "CausalGraphOwnershipContinuityError",
    "CausalIntervalClosureError",
    "CausalPropagationPolicyError",
    "CausalReconstructionSubstrateError",
    "ChronologyDegradationPropagationError",
    "ChronologyLegalityError",
    "CommitmentDerivedCausalityError",
    "CrossSystemTimeReconciliationError",
    "DeterministicCausalChainError",
    "ExecutionCausalityConstraintError",
    "IntervalContinuityError",
    "NegativeSignalCausalityError",
    "OrganizationalContinuityReasoningError",
    "ProofBundleCompositionError",
    "ReasoningCognitionLeakageError",
    "ReasoningGoldenThreadCorpusBindingError",
    "ReasoningProvenanceLawError",
    "ReasoningReceiptsProofArtifactsError",
    "ReplayChronologyError",
    "ReplayEquivalenceProofsError",
    "ReplaySafeReasoningPostureError",
    "TemporalAnchorResolutionError",
    "TemporalConflictResolutionError",
    "TemporalReasoningInvariantError",
    "UnverifiableDegradedCausalityError",
    "build_proof_bundle_inner_digest_body_v1",
    "build_org_graph_reasoning_verification_slice_v1",
    "build_reasoning_certification_pack_snapshot_v1",
    "build_reasoning_control_plane_catalog_v1",
    "build_reasoning_readiness_economics_receipt_v1",
    "build_reasoning_runtime_legality_matrix_catalog_v1",
    "build_tcre_cert_pack_v1",
    "bind_reasoning_golden_corpus_at_root_v1",
    "chronology_projection_matched_row_canonical_index",
    "chronology_projection_snapshot_from_temporal_conflict_v1",
    "canonical_breakpoint_id_body_v1",
    "canonical_reasoning_replay_permutation_v1_json",
    "canonical_sorted_tcre_causal_edge_ids_v1",
    "causal_chain_id_canonical_body_v1",
    "compare_gp06_replay_01_double_run_v1",
    "compute_reasoning_economics_receipt_hash_v1",
    "compute_reasoning_verification_slice_hash_v1",
    "coordination_edge_kind_is_known",
    "continuity_bridge_strength_rank_v1",
    "continuity_bridge_strictly_stronger_v1",
    "cross_system_causal_effective_min_rank_v1",
    "effective_max_causal_hops_v1",
    "declare_replay_safe_ordering_v1",
    "default_severity_for_reasoning_gate_v1",
    "default_reasoning_policy_pack_path",
    "degradation_coarse_tag_v1",
    "degradation_receipt_entry_v1",
    "degradation_severity_rank_v1",
    "find_chronology_skew_projection_row",
    "hash_causal_chain_id_v1",
    "hash_breakpoint_id_v1",
    "hash_pinned_replay_chronology_tuple_v1",
    "hash_proof_bundle_inner_digest_v1",
    "hash_reasoning_canonical_json_sha256_v1",
    "hash_reasoning_corpus_manifest_digest_v1",
    "hash_reasoning_receipt_canonical_v1",
    "list_lrel_forbidden_keys_on_mapping",
    "list_cd_chron_from_chronology_legality_v1",
    "list_fs_rtv01_slice_float_violations_v1",
    "lineage_includes_commitment_contract_hop_v1",
    "lineage_includes_negative_signal_contract_hop_v1",
    "lineage_includes_raw_record_hop_negative_v1",
    "lineage_includes_raw_record_hop_v1",
    "load_default_reasoning_policy_pack",
    "load_reasoning_corpus_case_v1",
    "load_reasoning_corpus_manifest_v1",
    "max_underlying_coordination_edges_for_tcre_kind_v1",
    "normalize_ambiguity_corpus_token_to_registry_id_v1",
    "normalize_cd_corpus_tokens_sorted_unique_v1",
    "normalize_degradation_corpus_token_v1",
    "normalize_expected_degradation_classes_corpus_v1",
    "normalize_gp06_replay_01_comparison_vector_v1",
    "normalize_observed_at_iso",
    "project_chronology_legality_class_v1",
    "primary_tcre_kind_for_coordination_edge_kind_v1",
    "reject_median_time_resolution_heuristic",
    "resolve_negative_signal_kind_v1",
    "resolve_temporal_anchor_chain_v1",
    "reasoning_ambiguity_receipt_body_v1",
    "reasoning_causal_receipt_body_v1",
    "reasoning_chronology_receipt_body_v1",
    "reasoning_equivalence_receipt_body_v1",
    "reasoning_gp06_ci_full_stage_row_map_v1",
    "reasoning_gp06_gate_stage_v1",
    "reasoning_golden_vectors_v1_root",
    "reasoning_provenance_minimal_valid_fixture_v1",
    "reasoning_replay_receipt_body_v1",
    "reasoning_tenant_verification_slice_enabled_v1",
    "run_reasoning_gp06_ci_full_az_topology_with_meta_v1",
    "run_reasoning_gp06_ci_full_wired_stages_with_meta_v1",
    "run_reasoning_gp06_ci_pr_blocking_bundle_v1",
    "run_reasoning_gp06_pr_blocking_static_stages_v1",
    "run_reasoning_gp06_wired_verification_stages_v1",
    "should_emit_cd_chron_from_policy",
    "skew_flag_tuple_from_reasoning_snapshot_v1",
    "sort_breakpoint_index_rows_v1",
    "sort_cd_codes_deg_mon_1_display_v1",
    "sort_anchors_temporal_anchor_resolution_order_v1",
    "sort_degradation_receipt_entries_v1",
    "temporal_anchor_resolution_sort_key_v1",
    "temporal_conflict_precedence_rank_v1",
    "tcre_edge_cites_concrete_coordination_edge_ids_v1",
    "underlying_coordination_edge_ids_sentinel_only_negative_v1",
    "underlying_coordination_edge_ids_sentinel_only_v1",
    "validate_ambiguity_class_id_causal_registry_v1",
    "validate_ambiguity_class_id_registered",
    "validate_amb_s1_no_false_certainty_coercion_v1",
    "validate_authoritative_link_gates_for_tcre_support",
    "validate_candidate_or_hint_not_sole_without_bridge_weak",
    "validate_evidence_lineage_has_raw_or_ledger_hop",
    "validate_replay_conflicted_walk_propagates",
    "list_reasoning_forbidden_cognition_key_violations",
    "list_reasoning_package_banned_import_violations",
    "list_reasoning_gp06_ci_stage_letters_ordered_v1",
    "list_reasoning_gp06_doctrine_gate_ids_v1",
    "list_reasoning_control_plane_surface_ids_v1",
    "list_reasoning_runtime_legality_predicate_ids_v1",
    "list_reasoning_gp06_wired_verification_runners_v1",
    "validate_breakpoint_index_sorted_v1",
    "validate_causal_legality_class",
    "validate_causal_influence_half_open_chain_v1",
    "validate_causal_ambiguity_propagation_bundle_v1",
    "validate_cd_multiset_monotonic_extension_degraded_v1",
    "validate_cross_source_temporal_reference_contract",
    "validate_cross_system_causal_continuity_requirements_v1",
    "validate_cross_system_tcre_support_not_weak_only_v1",
    "validate_degradation_multiset_monotonic_extension_v1",
    "validate_degradation_receipt_entries_sorted_v1",
    "validate_drift_degradation_receipt_links_breakpoints_v1",
    "validate_export_vs_observed_conflict_flags_v1",
    "validate_gp06_replay_01_equivalence_claim_scope_v1",
    "validate_half_open_interval_chain_continuity_v1",
    "validate_half_open_interval_iso",
    "validate_interval_graph_and_emit_chronology_receipt_v1",
    "validate_late_arrival_append_only",
    "validate_merge_rules_coordination_edges_v1",
    "validate_no_replay_safe_ordering_mutation_claim",
    "validate_parent_artifact_ids_sorted_unique",
    "validate_proof_bundle_equivalence_receipt_set_v1",
    "validate_policy_caps_g_p06_pol01_v1",
    "validate_pinned_replay_chronology_tuple_v1",
    "validate_propagation_rule_table_v1_when_present",
    "validate_reasoning_artifact_provenance_envelope_v1",
    "validate_reasoning_canonical_json_mapping_no_cognition_leakage",
    "validate_org_graph_reasoning_verification_slice_v1",
    "validate_reasoning_corpus_case_header_v1",
    "validate_reasoning_corpus_manifest_v1",
    "validate_reasoning_receipt_type_literal_v1",
    "validate_reasoning_interval_has_anchor_or_raw_lineage",
    "validate_reasoning_interval_slice_half_open_v1",
    "validate_reasoning_replay_permutation_v1_json",
    "validate_replay_safe_ordering_read_only_value",
    "validate_replay_safe_reasoning_posture_from_mapping_v1",
    "validate_replay_safe_reasoning_posture_v1",
    "validate_temporal_anchor_resolution_inputs_v1",
    "validate_tcre_policy_bundle_digest_shape_v1",
    "validate_tcre_payload_excludes_coordination_edge_shape_v1",
    "validate_temporal_active_conflict_classes_v1",
    "validate_temporal_conflict_no_history_rewrite_v1",
    "validate_tcre_causal_edge_v1_reconstruction_substrate",
    "validate_tcre_causal_edge_v1_reconstruction_substrate_commitment_transition_v1",
    "validate_tcre_causal_edge_v1_reconstruction_substrate_negative_signal_v1",
    "validate_tcre_causal_edge_v1_reconstruction_substrate_with_ownership_v1",
    "validate_tcre_causal_graph_ownership_continuity_v1",
    "validate_tcre_commitment_transition_causality_v1",
    "validate_tcre_commitment_transition_derivation_rule_v1",
    "validate_tcre_commitment_transition_sentinel_lineage_v1",
    "validate_tcre_edge_v1_stub",
    "validate_tcre_edge_v1_stub_with_propagation_policy_v1",
    "validate_tcre_negative_signal_causality_v1",
    "validate_tcre_negative_signal_derivation_rule_v1",
    "validate_tcre_negative_signal_kind_silence_law_v1",
    "validate_tcre_negative_signal_sentinel_lineage_v1",
    "validate_underlying_coordination_edge_ids_propagation_v1",
    "validate_unverifiable_causality_requires_cd_codes_v1",
    "validate_chron_forb1",
    "validate_chronology_allows_strict_temporal_order_claim_v1",
    "validate_chronology_snapshot_matches_pinned_replay_tuple_v1",
    "validate_chronology_snapshot_read_only_replay_safe_ordering_v1",
    "validate_chronology_strict_requires_resolved_pairs_v1",
    "verify_causal_chain_id_v1",
    "verify_default_policy_pack_digest",
    "verify_gp06_amb01_registry_literal_oracle_static",
    "verify_gp06_amb02_legacy_alias_normalization_static",
    "verify_gp06_amb03_unknown_corpus_token_rejected_static",
    "verify_gp06_amb04_amb_s1_rejects_coercion_flags_static",
    "verify_gp06_amb05_bundle_happy_path_static",
    "verify_gp06_anti01_reasoning_package_static",
    "verify_gp06_cont01_authoritative_link_gate_static",
    "verify_gp06_cont02_candidate_hint_sole_static",
    "verify_gp06_cont03_evidence_lineage_substrate_static",
    "verify_gp06_cont04_replay_conflicted_propagation_static",
    "verify_gp06_ecc01_causal_legality_enum_static",
    "verify_gp06_ecc02_parent_artifact_ids_static",
    "verify_gp06_ecc03_tcre_edge_shape_static",
    "verify_gp06_cia01_full_stage_row_partition_covers_doctrine_static",
    "verify_gp06_cia02_pr_blocking_stages_match_constant_and_underlying_static",
    "verify_gp06_cia03_severity_defaults_hard_fail_all_doctrine_static",
    "verify_gp06_cia04_wired_runner_keys_equal_doctrine_static",
    "verify_gp06_cia05_full_az_topology_including_empty_rows_passes_static",
    "verify_gp06_cia06_close_gate_is_last_in_stage_z_static",
    "verify_gp06_cia07_phase05_doc_anchor_present_static",
    "verify_gp06_cia08_ci_invariant_literal_frozen_static",
    "verify_gp06_chron01_default_policy_rows_static",
    "verify_gp06_chron02_projection_closure_static",
    "verify_gp06_cmt01_sentinel_requires_raw_and_commitment_hop_static",
    "verify_gp06_cmt02_concrete_coordination_skips_extra_commitment_hop_static",
    "verify_gp06_cmt03_bad_derivation_rule_prefix_rejected_static",
    "verify_gp06_cmt04_wrong_kind_rejected_static",
    "verify_gp06_cmt05_substrate_plus_commitment_law_static",
    "verify_gp06_cic01_default_policy_caps_static",
    "verify_gp06_cic02_half_open_closure_oracle_static",
    "verify_gp06_cic03_hop_cap_exceeded_static",
    "verify_gp06_cdp01_breakpoint_id_body_key_oracle_static",
    "verify_gp06_cdp02_breakpoint_index_sort_stable_static",
    "verify_gp06_cdp03_drift_receipt_requires_sorted_cd_static",
    "verify_gp06_cdp04_breakpoint_id_roundtrip_static",
    "verify_gp06_cdp05_policy_digest_shape_enforced_static",
    "verify_gp06_clc01_literal_table_oracle_static",
    "verify_gp06_clc02_tcre_stub_accepts_each_legal_literal_static",
    "verify_gp06_clc03_tcre_stub_rejects_unknown_causal_legality_static",
    "verify_gp06_clc04_tcre_stub_omits_causal_legality_class_static",
    "verify_gp06_close01_tcre_cert_pack_closure_static",
    "verify_gp06_close01_tcre_cert_pack_shape_reference_static",
    "verify_gp06_neg01_sentinel_requires_raw_and_signal_hop_static",
    "verify_gp06_neg02_concrete_coordination_skips_extra_signal_hop_static",
    "verify_gp06_neg03_bad_derivation_rule_prefix_rejected_static",
    "verify_gp06_neg04_unlawful_negative_signal_kind_rejected_static",
    "verify_gp06_neg05_substrate_plus_negative_signal_law_static",
    "verify_gp06_crs01_coordination_to_tcre_primary_map_static",
    "verify_gp06_crs02_reconstruction_requires_confidence_static",
    "verify_gp06_crs03_cross_system_weak_only_guard_static",
    "verify_gp06_crs04_option_a_rejects_coordination_edge_kind_key_static",
    "verify_gp06_dcc01_causal_chain_id_permutation_invariant_static",
    "verify_gp06_dcc02_policy_digest_participates_static",
    "verify_gp06_dcc03_canonical_body_sorted_keys_static",
    "verify_gp06_edp01_default_pack_merge_rules_static",
    "verify_gp06_edp02_merge_cap_multi_id_oracle_static",
    "verify_gp06_edp03_default_stub_conflict_with_multi_id_resolved_static",
    "verify_gp06_deg01_corpus_alias_registry_static",
    "verify_gp06_deg02_severity_sort_oracle_static",
    "verify_gp06_deg03_default_policy_caps_static",
    "verify_gp06_udc01_canonical_cd_literal_oracle_static",
    "verify_gp06_udc02_severity_rank_table_oracle_static",
    "verify_gp06_udc03_monotonic_regression_rejected_static",
    "verify_gp06_udc04_unverifiable_requires_cd_static",
    "verify_gp06_udc05_degradation_receipt_sort_stable_static",
    "verify_gp06_xst01_rank_table_oracle_static",
    "verify_gp06_xst02_default_policy_min_rank_static",
    "verify_gp06_xst03_cross_caus_rank4_derivation_gate_static",
    "verify_gp06_int01_half_open_chain_continuity_static",
    "verify_gp06_int02_chronology_receipt_projection_static",
    "verify_gp06_own01_concrete_ids_require_authoritative_org_support_static",
    "verify_gp06_own02_sentinel_path_skips_org_link_support_static",
    "verify_gp06_own03_non_authoritative_org_support_rejected_static",
    "verify_gp06_own04_substrate_plus_ownership_combined_entry_static",
    "verify_gp06_pbc01_inner_body_sorted_pairs_oracle_static",
    "verify_gp06_pbc02_equivalence_receipt_always_required_static",
    "verify_gp06_pbc03_chronology_required_when_participates_static",
    "verify_gp06_pbc04_inner_hash_permutation_invariant_static",
    "verify_gp06_pbc05_full_minimal_bundle_validates_static",
    "verify_gp06_rep01_permutation_canonical_static",
    "verify_gp06_rep02_pinned_tuple_hash_static",
    "verify_gp06_json_cognition_keys_static",
    "verify_gp06_rpl01_replay_posture_literal_oracle_static",
    "verify_gp06_rpl02_minimal_envelope_happy_path_static",
    "verify_gp06_rpl03_missing_lineage_rejected_static",
    "verify_gp06_rpl04_cross_system_requires_org_link_static",
    "verify_gp06_rpl05_deprecated_degradation_semantics_rejected_static",
    "verify_gp06_rra01_receipt_type_catalog_oracle_static",
    "verify_gp06_rra02_canonical_hash_stable_under_key_order_static",
    "verify_gp06_rra03_causal_receipt_sorted_ids_enforced_static",
    "verify_gp06_rra04_ambiguity_receipt_happy_path_static",
    "verify_gp06_rra05_equivalence_receipt_happy_path_static",
    "verify_gp06_req01_replay_01_gate_id_oracle_static",
    "verify_gp06_req02_permutation_profile_id_literal_static",
    "verify_gp06_req03_minimal_bundle_double_run_match_static",
    "verify_gp06_req04_chronology_digest_required_when_participates_static",
    "verify_gp06_req05_double_run_mismatch_raises_static",
    "verify_gp06_req06_causal_only_insufficient_when_receipts_static",
    "verify_gp06_rsp01_replay_safe_posture_happy_path_static",
    "verify_gp06_rsp02_policy_digest_shape_rejected_static",
    "verify_gp06_rsp03_permutation_profile_id_enforced_static",
    "verify_gp06_rsp04_pinned_tuple_hash_stable_under_posture_static",
    "verify_gp06_rtvs01_org_graph_reasoning_slice_golden_static",
    "verify_gp06_rtvs02_admin_openapi_path_matrix_static",
    "verify_gp06_rvh01_harness_catalog_covers_spec_gate_table_static",
    "verify_gp06_rvh02_pr_blocking_bundle_passes_static",
    "verify_gp06_rvh03_full_stage_az_includes_close_static",
    "verify_gp06_rcp01_surface_catalog_sorted_unique_static",
    "verify_gp06_rcp02_surfaces_match_admin_spec_table_static",
    "verify_gp06_rcp03_doctrine_refs_frozen_static",
    "verify_gp06_rcp04_build_catalog_contract_shape_static",
    "verify_gp06_rcp05_admin_openapi_path_matrix_static",
    "verify_gp06_rcp06_rbac_substrate_literal_frozen_static",
    "verify_gp06_rcpk01_reasoning_cert_pack_admin_openapi_path_matrix_static",
    "verify_gp06_rlm01_predicate_catalog_five_sorted_unique_static",
    "verify_gp06_rlm02_r_leg02_anti01_ci_green_static",
    "verify_gp06_rlm03_cross_doc_anchors_frozen_static",
    "verify_gp06_rlm04_forbidden_deployments_shape_static",
    "verify_gp06_rlm05_waiver_yaml_future_path_literal_static",
    "verify_gp06_rlm06_build_catalog_contract_shape_static",
    "verify_gp06_rlm07_admin_openapi_path_matrix_static",
    "verify_gp06_rreco01_readiness_economics_clean_profile_static",
    "verify_gp06_rreco02_readiness_economics_hostile_profile_static",
    "verify_gp06_rreco03_admin_openapi_path_matrix_static",
    "verify_gp06_gtc01_default_manifest_shape_static",
    "verify_gp06_gtc02_case_ambiguity_binding_static",
    "verify_gp06_gtc03_case_degradation_cd_binding_static",
    "verify_gp06_gtc04_optional_tcre_chains_shape_static",
    "verify_gp06_gtc05_full_bind_roundtrip_static",
    "verify_reasoning_gp06_corruption_bundles_subset_static",
    "verify_reasoning_gp06_gate_catalog_unique_ids_static",
    "verify_reasoning_gp06_wired_runner_gate_ids_match_static",
    "verify_gp06_tar01_resolution_order_literal_static",
    "verify_gp06_tar02_declare_replay_safe_ordering_static",
    "verify_gp06_tcr01_precedence_oracle_static",
    "verify_gp06_tcr02_chronology_strict_pairwise_static",
    "verify_gp06_tcr03_conflict_class_registry_static",
    "verify_gp06_tr01_interval_lineage_static",
    "verify_gp06_tr02_late_arrival_append_static",
    "verify_gp06_tr03_cross_source_reference_static",
    "verify_gp06_tr04_half_open_interval_static",
    "verify_tcre_cert_pack_v1",
)
