"""Phase 05 — Organizational Continuity Traversal Substrate (OCTS).

Step 1 (P05-01): normative index + program freeze — ``normative.PHASE05_PROGRAM_FREEZE_VERSION``.
Step 2 (P05-02): observed vs derived — ``observed_vs_derived`` validators + static gates.
Step 3 (P05-03): anti-goals — ``anti_goals`` cognition key scan + ingress token gate.
Step 4 (P05-04): graph import boundary — ``graph_import_boundary`` (GIB-01, FS-GIB-02/03,
``G-P05-IMPORT-01`` / ``G-P05-IMPORT-02``).
Step 5 (P05-05): traversal vs reasoning — ``traversal_vs_reasoning`` (TVR strict +
``G-P05-SCHEMA-01``).
Step 6 (P05-06): multigraph model — ``multigraph_model`` (**RULE MG-01/02**, **FS-MG-01**,
``G-P05-MG-01`` / ``G-P05-MG-02``).
Step 7 (P05-07): temporal walk — ``temporal_walk`` (**TA-01**, **RULE TW-02**, **G-P05-TEMP-01** /
``G-P05-TEMP-02``).
Step 8 (P05-08): walk policy — ``walk_policy`` (**RULE WP-01/02**, **FS-WP-01..03**,
``G-P05-POL-01`` / ``G-P05-POL-02``).
Step 9 (P05-09): walk result contract — ``walk_result_contract`` (**RULE WR-01/02**,
``G-P05-HASH-01`` / ``G-P05-HASH-02``).
Step 10 (P05-10): hop receipt — ``hop_receipt_contract`` (**RULE HR-01/02**, **FS-HR-01..03**,
``G-P05-HR-01`` / ``G-P05-HR-02``).
Step 11 (P05-11): exploration mode — ``exploration_mode_contract`` (**RULE EX-01/02**, **FS-EX-02**,
``G-P05-EXP-01`` / ``G-P05-EXP-02``; **EX-P1..P7** naming constants).
Step 12 (P05-12): walk diagnostics — ``walk_diagnostics_contract`` (**RULE WD-01**,
**FS-WD-01..03**, ``G-P05-DIAG-01`` / ``G-P05-DIAG-02``); optional ``skip_reason`` on hop receipts.
Step 13 (P05-13): derived index contract — ``derived_index_contract`` (**RULE DI-01/02**,
**FS-DI-01..03**, ``G-P05-IDX-01`` / ``G-P05-IDX-02``).
Step 14 (P05-14): index build job — ``index_build_job_contract`` (**RULE IBJ-01/02**,
**FS-IBJ-01..03**, ``G-P05-JOB-01`` / ``G-P05-JOB-02``).
Step 15 (P05-15): walk execution strategy — ``walk_execution_strategy_contract``
(**RULE WES-01/02**, **FS-WES-01..03**, ``G-P05-EQUIV-01``, ``G-P05-WES-01`` / ``G-P05-WES-02``).
Step 16 (P05-16): traversal engine runtime — ``runtime_execution_model``
(**RULE REM-01/02**, **FS-REM-01..02**, ``G-P05-RT-01`` / ``G-P05-RT-02``).
Step 17 (P05-17): walk HTTP API — ``walk_api_contract`` + admin routes (**RULE API-0**,
**RULE API-ERR**, ``G-P05-API-01`` / ``G-P05-API-02``); OpenAPI generator.
Step 18 (P05-18): sync walk limits — JSON byte caps + policy caps (**FS-API-01**, ``G-P05-API-03``);
``walk_policy`` exports **SYNC_MAX_*** including **SYNC_MAX_RESPONSE_JSON_BYTES**.
Step 19 (P05-19): walk replay — ``walk_replay_contract`` (**``inherit_walk_id``** resolution,
telemetry lineage per **``phase-05-walk-replay-doctrine.md``**).
Step 20 (P05-20): index replay — ``index_replay_contract`` (**``index_content_hash``** double-run /
lineage gates + admin **POST …/derived-index/replay-verify** per **``phase-05-index-replay-doctrine.md``**).
Step 21 (P05-21): traversal equivalence — ``traversal_equivalence_contract`` (**L-EQ-01..03**,
**ENG-01..03**, **G-P05-ENG-01**, **FS-TE-01/02** helpers, admin **GET …/engine-identity**, optional
``VECTOR_OCTS_ENFORCE_ENGINE_IDENTITY`` on sync authoritative walks per **``phase-05-traversal-equivalence-doctrine.md``**).
Step 22 (P05-22): verification gates catalog — ``verification_gates_catalog`` (**``G-P05-*** registry**,
corruption bundles, **STAGE-A–D** wired static runners, **G-P05-CANON-01..03**, **G-P05-LEGAL-01**,
**G-P05-RANK-01**, **G-P05-EQUIV-03** extensions, **``test_octs_stage_{a,b,c}.py``**) per
**``phase-05-verification-gates-doctrine.md``** + **``phase-05-ci-enforcement-architecture.md``**.
Step 23 (P05-23): tenant verification integration — ``tenant_verification_slice`` (**``org_graph_traversal``**
aggregate + **``octs_slice_hash``**, **G-P05-TVER-01**, env **``VECTOR_OCTS_TENANT_VERIFICATION_SLICE``**) per
**``phase-05-tenant-verification-integration.md``** (wired into ``identity.verification``).
Step 24 (P05-24): traversal control plane — ``traversal_control_plane`` (**structural queue / abort classes /
budget histogram**, **G-P05-CP-01**, env **``VECTOR_OCTS_CONTROL_PLANE_SHOW_EXPLORATION``**) per
**``phase-05-control-plane-doctrine.md``**.
Step 25 (P05-25): readiness + economics — ``traversal_readiness_economics`` (**numeric receipts**,
**``economics_receipt_hash``**, **G-P05-ECO-01** / **G-P05-ECO-02** / **G-P05-ECO-03**, admin
**``GET …/readiness-economics``**) per **``phase-05-readiness-economics-doctrine.md``**.
"""

from vector.domains.cortex.traversal.anti_goals import (
    ANTI_GOALS_RUNTIME_SCHEMA_VERSION,
    CognitionLeakageError,
    list_forbidden_cognition_key_violations,
    validate_octs_canonical_json_mapping_no_cognition_leakage,
    verify_gp05_anti01_forbidden_cognition_keys_static,
    verify_gp05_anti02_traversal_ingress_no_phase03_tokens_static,
)
from vector.domains.cortex.traversal.derived_index_contract import (
    DERIVED_INDEX_CANON_VERSION,
    DI_RUNTIME_SCHEMA_VERSION,
    PUBLISH_STATE_BUILDING,
    PUBLISH_STATE_PUBLISHED,
    DerivedIndexContractError,
    assert_index_content_hash_string_v1,
    canonical_derived_index_artifact_json_bytes_v1,
    compute_index_content_hash_v1,
    list_fs_di01_derived_edge_lineage_violations,
    list_fs_di03_index_epoch_regression_violations,
    octs_derived_index_fixture_dir,
    validate_derived_index_artifact_contract_v1,
    validate_publish_barrier_record_v1,
    validate_stale_derived_read_policy_v1,
    verify_gp05_idx01_index_content_hash_stability_static,
    verify_gp05_idx02_lineage_completeness_static,
)
from vector.domains.cortex.traversal.exploration_mode_contract import (
    CACHE_KEY_PREFIX_AUTHORITATIVE,
    CACHE_KEY_PREFIX_EXPLORATION,
    CELERY_QUEUE_AUTHORITATIVE,
    CELERY_QUEUE_EXPLORATION,
    CODEC_CLASS_AUTHORITATIVE,
    CODEC_CLASS_EXPLORATION,
    EX_RUNTIME_SCHEMA_VERSION,
    EXECUTION_PARTITION_AUTHORITATIVE,
    EXECUTION_PARTITION_DERIVED_AUDIT,
    EXECUTION_PARTITION_EXPLORATION,
    EXECUTION_PARTITION_VALUES,
    OTEL_EXPLORATION_SINK_NAME,
    TABLE_CORTEX_OCTS_WALK_AUTHORITATIVE,
    TABLE_CORTEX_OCTS_WALK_EXPLORATION,
    ExplorationModeContractError,
    assert_redis_cache_key_namespace_v1,
    exploration_partition_id_v1,
    octs_exploration_fixture_dir,
    validate_execution_partition_enum_v1,
    validate_exploration_hash_body_invariants_v1,
    validate_row_destination_exploration_law_v1,
    verify_gp05_exp01_walk_request_explicit_exploration_mode_static,
    verify_gp05_exp02_authoritative_table_rejects_exploration_partition_static,
)
from vector.domains.cortex.traversal.graph_import_boundary import (
    GIB_RUNTIME_SCHEMA_VERSION,
    GraphImportBoundaryError,
    list_oct_graph_import_violations,
    list_oct_traversal_ingress_token_violations,
    validate_inner_projection_matches_stable_hash,
    validate_oct_traversal_import_projection,
    validate_temporal_anchor_has_projection_content_hash,
    verify_gp05_import01_traversable_subset_authoritative_static,
    verify_gp05_import02_forbidden_ingress_tokens_static,
)
from vector.domains.cortex.traversal.hop_receipt_contract import (
    HR_RUNTIME_SCHEMA_VERSION,
    HopReceiptContractError,
    extract_evidence_envelope_v1,
    octs_hop_receipt_fixture_dir,
    recomputed_edge_fingerprint_from_receipt_v1,
    validate_hop_receipt_list_contract_v1,
    validate_hop_receipt_list_for_hash_body_v1,
    verify_gp05_hr01_fingerprint_recompute_from_envelope_static,
    verify_gp05_hr02_dangling_org_link_rejected_static,
)
from vector.domains.cortex.traversal.index_build_job_contract import (
    IBJ_RUNTIME_SCHEMA_VERSION,
    INDEX_BUILD_JOB_STATE_BUILDING,
    INDEX_BUILD_JOB_STATE_COMMITTED,
    INDEX_BUILD_JOB_STATE_FAILED,
    INDEX_BUILD_JOB_STATE_PUBLISHING,
    INDEX_BUILD_JOB_STATE_QUEUED,
    INDEX_BUILD_JOB_STATE_VALIDATING,
    INDEX_BUILD_JOB_STATES_V1,
    IndexBuildJobContractError,
    compute_index_build_idempotency_key_v1,
    list_fs_ibj02_duplicate_committed_epoch_different_hash_violations,
    list_rule_ibj01_simultaneous_building_lease_violations,
    octs_index_build_job_fixture_dir,
    validate_fs_ibj03_shadow_store_visibility_v1,
    validate_index_build_completion_events_v1,
    validate_index_build_job_receipt_v1,
    validate_index_build_job_state_sequence_v1,
    validate_index_build_job_state_transition_v1,
    verify_gp05_job01_index_build_fsm_illegal_transitions_static,
    verify_gp05_job02_validating_publish_audit_static,
)
from vector.domains.cortex.traversal.multigraph_model import (
    MG_RUNTIME_SCHEMA_VERSION,
    MultigraphModelError,
    canonical_diagnostic_multiset_fingerprints_v1,
    compute_edge_fingerprint_v1,
    edge_eligible_at_t_as_of_unix_ns,
    list_fs_mg01_duplicate_fingerprint_violations,
    neighbor_expansion_fingerprints_ordered_v1,
    octs_multigraph_neighbor_order_fixture_dir,
    verify_gp05_mg01_neighbor_order_golden_static,
    verify_gp05_mg02_fingerprint_uniqueness_static,
)
from vector.domains.cortex.traversal.normative import PHASE05_PROGRAM_FREEZE_VERSION
from vector.domains.cortex.traversal.observed_vs_derived import (
    OVD_RUNTIME_SCHEMA_VERSION,
    PROVENANCE_CLASS_DERIVED,
    PROVENANCE_CLASS_OBSERVED,
    WALK_EXECUTION_STRATEGY_HYBRID_PINNED,
    WALK_EXECUTION_STRATEGY_MATERIALIZED_DERIVED,
    WALK_EXECUTION_STRATEGY_ONLINE_OBSERVED,
    ObservedDerivedInvariantError,
    validate_hop_receipt_observed_derived,
    validate_hop_receipt_sequence,
    validate_walk_observed_derived_consistency,
    verify_gp05_ovd01_observed_hop_bindings_static,
    verify_gp05_ovd02_strategy_and_derived_flags_static,
)
from vector.domains.cortex.traversal.runtime_execution_model import (
    REM_RUNTIME_SCHEMA_VERSION,
    RuntimeExecutionModelError,
    list_fs_rem01_reference_walk_artifact_forbidden_keys_v1,
    octs_runtime_execution_fixture_dir,
    path_context_id_v1,
    run_reference_frontier_walk_v1,
    verify_gp05_rt01_engine_determinism_static,
    verify_gp05_rt02_frontier_cap_budget_static,
)
from vector.domains.cortex.traversal.traversal_equivalence_contract import (
    OCTS_DEV_ENGINE_ID_ENV,
    OCTS_TRAVERSAL_EQUIVALENCE_CONTRACT_SCHEMA_VERSION,
    VECTOR_OCTS_EMBEDDED_GIT_SHA_ENV,
    VECTOR_OCTS_ENGINE_BUILD_ID_ENV,
    OctsEngineIdentityError,
    list_fs_te01_same_inputs_different_hash_violations_v1,
    list_fs_te02_fast_path_without_equiv_pass_violations_v1,
    resolve_oct_engine_build_id_v1,
    verify_gp05_eng01_engine_build_id_coherence_static,
    verify_leq01_walk_hash_double_run_stub_static,
    verify_leq02_async_job_order_independence_stub_static,
    verify_leq03_fast_path_equiv_obligation_static,
    verify_oct_traversal_equivalence_step21_static_bundle,
)
from vector.domains.cortex.traversal.verification_gates_catalog import (
    OCTS_CORRUPTION_GATE_BUNDLES_V1,
    OCTS_VERIFICATION_GATES_CATALOG_SCHEMA_VERSION,
    OctsGateCatalogEntryV1,
    default_severity_for_gate_v1,
    gate_stage_v1,
    list_octs_doctrine_gate_ids_v1,
    list_octs_gate_catalog_entries_v1,
    list_wired_verification_runners_v1,
    load_verification_waivers_v1,
    octs_golden_vectors_v1_root,
    run_octs_pr_blocking_static_stages_v1,
    run_octs_wired_verification_stages_v1,
    verification_waivers_yaml_path,
    verify_oct_verification_gates_step22_static_bundle,
    verify_octs_corruption_bundles_reference_known_gates_static,
    verify_octs_gate_catalog_unique_ids_static,
    verify_octs_waiver_entries_schema_static,
    verify_octs_waiver_yaml_parseable_static,
    verify_octs_wired_runner_gate_ids_match_static,
)
from vector.domains.cortex.traversal.tenant_verification_slice import (
    ORG_GRAPH_TRAVERSAL_VERIFICATION_SLICE_SCHEMA_VERSION,
    VECTOR_OCTS_TENANT_VERIFICATION_SLICE_ENV,
    build_org_graph_traversal_verification_slice_v1,
    compute_octs_slice_hash_v1,
    octs_golden_vectors_v1_root_for_tenant_slice,
    octs_org_graph_traversal_verification_slice_schema_path,
    octs_tenant_verification_slice_enabled_v1,
    validate_org_graph_traversal_verification_slice_v1,
    verify_gp05_tver01_org_graph_traversal_slice_golden_static,
)
from vector.domains.cortex.traversal.traversal_control_plane import (
    OCTS_TRAVERSAL_CONTROL_PLANE_CONTRACT,
    OCTS_TRAVERSAL_CONTROL_PLANE_SCHEMA_VERSION,
    VECTOR_OCTS_CONTROL_PLANE_SHOW_EXPLORATION_ENV,
    build_octs_traversal_control_plane_v1,
    octs_control_plane_show_exploration_v1,
    verify_gp05_cp01_traversal_control_plane_rbac_static,
    verify_octs_traversal_control_plane_v1_shape,
)
from vector.domains.cortex.traversal.traversal_readiness_economics import (
    OCTS_TRAVERSAL_READINESS_ECONOMICS_CONTRACT,
    OCTS_TRAVERSAL_READINESS_ECONOMICS_SCHEMA_VERSION,
    ProbeProfileV1,
    assert_hostile_hub_fixture_breaches_thresholds_v1,
    build_octs_traversal_readiness_economics_receipt_v1,
    compute_economics_receipt_hash_v1,
    octs_economics_golden_dir_v1,
    verify_gp05_eco01_max_out_degree_golden_static,
    verify_gp05_eco02_walk_wall_budget_golden_static,
    verify_gp05_eco03_derived_index_bytes_per_edge_golden_static,
    verify_octs_readiness_economics_receipt_v1_shape,
)
from vector.domains.cortex.traversal.temporal_walk import (
    MAX_CLOCK_SKEW_NS,
    TW_RUNTIME_SCHEMA_VERSION,
    TemporalWalkInvariantError,
    linearized_export_sequence_commits_v1,
    list_export_sequence_monotonicity_violations_v1,
    list_superseded_link_still_present_violations_v1,
    octs_temporal_fixture_dir,
    org_link_eligible_half_open_unix_ns_v1,
    temporal_anchor_canonical_json_bytes_v1,
    validate_graph_as_of_vs_snapshot_clock_skew_v1,
    validate_temporal_anchor_invariants_v1,
    verify_gp05_temp01_sequence_validity_supersession_static,
    verify_gp05_temp02_anchor_roundtrip_and_concurrency_static,
)
from vector.domains.cortex.traversal.traversal_vs_reasoning import (
    TVR_RUNTIME_SCHEMA_VERSION,
    WALK_RESULT_HASH_BODY_KEYS_V1,
    TraversalReasoningBoundaryError,
    list_walk_result_hash_body_unknown_keys_v1,
    load_oct_walk_request_v1_schema,
    oct_walk_request_minimal_fixture_path,
    oct_walk_request_v1_schema_path,
    validate_oct_walk_request_v1,
    validate_walk_result_hash_body_tvr_strict_v1,
    verify_gp05_schema01_oct_walk_request_v1_static,
    verify_gp05_tvr01_walk_result_hash_body_strict_static,
)
from vector.domains.cortex.traversal.walk_api_contract import (
    API_WALK_CONTRACT_SCHEMA_VERSION,
    OCTS_STUB_ENGINE_BUILD_ID,
    build_stub_completed_walk_payload_v1,
    canonical_octs_api_error_body_v1,
    canonical_octs_walk_api_json_utf8_len_v1,
    completed_sync_walk_api_public_document_v1,
    list_fs_api01_sync_request_json_cap_violations_v1,
    list_fs_api01_sync_response_json_cap_violations_v1,
    octs_walk_api_memory_store_v1,
    octs_walk_api_openapi_path,
    verify_gp05_api01_openapi_walk_paths_static,
    verify_gp05_api02_openapi_security_static,
    verify_gp05_api03_sync_walk_limits_static,
)
from vector.domains.cortex.traversal.walk_replay_contract import (
    OCTS_WALK_REPLAY_RESOLUTION_SCHEMA_VERSION,
    WalkReplayResolutionError,
    canonical_json_equality_v1,
    prepare_effective_oct_walk_request_v1,
    verify_oct_walk_replay_stub_inherit_resolution_static,
)
from vector.domains.cortex.traversal.index_replay_contract import (
    INDEX_REPLAY_CONTRACT_SCHEMA_VERSION,
    list_fs_irj02_incomplete_node_set_compare_violations_v1,
    load_oct_derived_index_replay_verify_v1_schema,
    oct_derived_index_replay_verify_v1_schema_path,
    validate_oct_derived_index_replay_verify_body_v1,
    verify_gp05_replay_idx01_double_run_equality_static,
    verify_gp05_replay_idx02_corrupt_lineage_deterministic_failure_static,
)
from vector.domains.cortex.traversal.walk_diagnostics_contract import (
    SKIP_REASON_VALUES_V1,
    TERMINATION_REASON_VALUES_V1,
    WD_RUNTIME_SCHEMA_VERSION,
    WalkDiagnosticsContractError,
    compute_cycle_fingerprint_v1,
    octs_walk_diagnostics_enums_schema_path,
    octs_walk_diagnostics_fixture_dir,
    validate_skip_reason_enum_v1,
    validate_termination_reason_enum_v1,
    validate_walk_diagnostics_hash_body_contract_v1,
    verify_gp05_diag01_enum_exhaustiveness_vs_schema_static,
    verify_gp05_diag02_cycle_fingerprint_golden_static,
)
from vector.domains.cortex.traversal.walk_execution_strategy_contract import (
    WES_RUNTIME_SCHEMA_VERSION,
    WalkExecutionStrategyContractError,
    list_fs_wes03_forbidden_optimization_keys_under_hash_body_v1,
    octs_walk_execution_strategy_fixture_dir,
    validate_fast_path_equivalence_record_v1,
    validate_fs_wes01_materialized_requires_pinned_index_epoch_v1,
    validate_hybrid_policy_integer_threshold_for_strategy_v1,
    validate_materialized_adjacency_hop_receipt_v1,
    validate_temporal_anchor_extension_sorted_keys_v1,
    verify_gp05_equiv01_fast_path_online_equivalence_static,
    verify_gp05_wes01_strategy_affects_policy_hash_static,
    verify_gp05_wes03_forbidden_optimization_hash_body_scan_static,
)
from vector.domains.cortex.traversal.walk_policy import (
    SYNC_MAX_EDGES_VISITED,
    SYNC_MAX_HOPS,
    SYNC_MAX_REQUEST_JSON_BYTES,
    SYNC_MAX_RESPONSE_JSON_BYTES,
    SYNC_MAX_WALL_MS,
    WP_RUNTIME_SCHEMA_VERSION,
    WalkPolicyInvariantError,
    compute_policy_hash_v1,
    list_walk_policy_sync_cap_violations_v1,
    oct_walk_policy_v1_schema_path,
    octs_walk_policy_fixture_dir,
    validate_oct_walk_policy_v1_jsonschema,
    validate_walk_policy_for_request_v1,
    verify_gp05_pol01_walk_policy_schema_and_hash_static,
    verify_gp05_pol02_sync_caps_reject_static,
    walk_policy_canonical_json_bytes_for_hash_v1,
)
from vector.domains.cortex.traversal.walk_result_contract import (
    WR_RUNTIME_SCHEMA_VERSION,
    WalkResultContractError,
    canonical_walk_result_hash_body_bytes_v1,
    compute_walk_result_hash_v1,
    extract_walk_result_hash_body_v1,
    list_fs_wr03_duplicate_hop_sequence_violations,
    list_wr02_forbidden_key_violations_under_hash_body,
    octs_walk_result_fixture_dir,
    validate_walk_result_hash_body_contract_v1,
    verify_gp05_hash01_walk_result_hash_recompute_static,
    verify_gp05_hash02_telemetry_separation_static,
)

__all__ = [
    "MAX_CLOCK_SKEW_NS",
    "TW_RUNTIME_SCHEMA_VERSION",
    "TemporalWalkInvariantError",
    "MG_RUNTIME_SCHEMA_VERSION",
    "MultigraphModelError",
    "ANTI_GOALS_RUNTIME_SCHEMA_VERSION",
    "API_WALK_CONTRACT_SCHEMA_VERSION",
    "CACHE_KEY_PREFIX_AUTHORITATIVE",
    "CACHE_KEY_PREFIX_EXPLORATION",
    "CELERY_QUEUE_AUTHORITATIVE",
    "CELERY_QUEUE_EXPLORATION",
    "CODEC_CLASS_AUTHORITATIVE",
    "CODEC_CLASS_EXPLORATION",
    "CognitionLeakageError",
    "DERIVED_INDEX_CANON_VERSION",
    "DI_RUNTIME_SCHEMA_VERSION",
    "DerivedIndexContractError",
    "EX_RUNTIME_SCHEMA_VERSION",
    "EXECUTION_PARTITION_AUTHORITATIVE",
    "EXECUTION_PARTITION_DERIVED_AUDIT",
    "EXECUTION_PARTITION_EXPLORATION",
    "EXECUTION_PARTITION_VALUES",
    "ExplorationModeContractError",
    "GIB_RUNTIME_SCHEMA_VERSION",
    "GraphImportBoundaryError",
    "HR_RUNTIME_SCHEMA_VERSION",
    "HopReceiptContractError",
    "IBJ_RUNTIME_SCHEMA_VERSION",
    "INDEX_BUILD_JOB_STATE_BUILDING",
    "INDEX_BUILD_JOB_STATE_COMMITTED",
    "INDEX_BUILD_JOB_STATE_FAILED",
    "INDEX_BUILD_JOB_STATE_PUBLISHING",
    "INDEX_BUILD_JOB_STATE_QUEUED",
    "INDEX_BUILD_JOB_STATE_VALIDATING",
    "INDEX_BUILD_JOB_STATES_V1",
    "INDEX_REPLAY_CONTRACT_SCHEMA_VERSION",
    "IndexBuildJobContractError",
    "OVD_RUNTIME_SCHEMA_VERSION",
    "OCTS_CORRUPTION_GATE_BUNDLES_V1",
    "OCTS_DEV_ENGINE_ID_ENV",
    "OCTS_STUB_ENGINE_BUILD_ID",
    "OCTS_TRAVERSAL_EQUIVALENCE_CONTRACT_SCHEMA_VERSION",
    "OCTS_VERIFICATION_GATES_CATALOG_SCHEMA_VERSION",
    "OCTS_TRAVERSAL_CONTROL_PLANE_CONTRACT",
    "OCTS_TRAVERSAL_CONTROL_PLANE_SCHEMA_VERSION",
    "OCTS_TRAVERSAL_READINESS_ECONOMICS_CONTRACT",
    "OCTS_TRAVERSAL_READINESS_ECONOMICS_SCHEMA_VERSION",
    "ORG_GRAPH_TRAVERSAL_VERIFICATION_SLICE_SCHEMA_VERSION",
    "OCTS_WALK_REPLAY_RESOLUTION_SCHEMA_VERSION",
    "ProbeProfileV1",
    "PROVENANCE_CLASS_DERIVED",
    "PROVENANCE_CLASS_OBSERVED",
    "PHASE05_PROGRAM_FREEZE_VERSION",
    "REM_RUNTIME_SCHEMA_VERSION",
    "PUBLISH_STATE_BUILDING",
    "PUBLISH_STATE_PUBLISHED",
    "TABLE_CORTEX_OCTS_WALK_AUTHORITATIVE",
    "TABLE_CORTEX_OCTS_WALK_EXPLORATION",
    "TVR_RUNTIME_SCHEMA_VERSION",
    "TraversalReasoningBoundaryError",
    "VECTOR_OCTS_EMBEDDED_GIT_SHA_ENV",
    "VECTOR_OCTS_ENGINE_BUILD_ID_ENV",
    "VECTOR_OCTS_TENANT_VERIFICATION_SLICE_ENV",
    "VECTOR_OCTS_CONTROL_PLANE_SHOW_EXPLORATION_ENV",
    "WALK_RESULT_HASH_BODY_KEYS_V1",
    "SYNC_MAX_EDGES_VISITED",
    "SYNC_MAX_HOPS",
    "SYNC_MAX_REQUEST_JSON_BYTES",
    "SYNC_MAX_RESPONSE_JSON_BYTES",
    "SYNC_MAX_WALL_MS",
    "SKIP_REASON_VALUES_V1",
    "TERMINATION_REASON_VALUES_V1",
    "WP_RUNTIME_SCHEMA_VERSION",
    "WES_RUNTIME_SCHEMA_VERSION",
    "RuntimeExecutionModelError",
    "WalkDiagnosticsContractError",
    "WalkExecutionStrategyContractError",
    "WalkPolicyInvariantError",
    "WalkReplayResolutionError",
    "WalkResultContractError",
    "WD_RUNTIME_SCHEMA_VERSION",
    "WR_RUNTIME_SCHEMA_VERSION",
    "assert_hostile_hub_fixture_breaches_thresholds_v1",
    "assert_index_content_hash_string_v1",
    "assert_redis_cache_key_namespace_v1",
    "build_stub_completed_walk_payload_v1",
    "build_org_graph_traversal_verification_slice_v1",
    "build_octs_traversal_control_plane_v1",
    "build_octs_traversal_readiness_economics_receipt_v1",
    "canonical_diagnostic_multiset_fingerprints_v1",
    "canonical_json_equality_v1",
    "canonical_octs_api_error_body_v1",
    "canonical_octs_walk_api_json_utf8_len_v1",
    "canonical_walk_result_hash_body_bytes_v1",
    "compute_economics_receipt_hash_v1",
    "compute_edge_fingerprint_v1",
    "compute_cycle_fingerprint_v1",
    "compute_index_content_hash_v1",
    "compute_index_build_idempotency_key_v1",
    "compute_octs_slice_hash_v1",
    "compute_policy_hash_v1",
    "compute_walk_result_hash_v1",
    "completed_sync_walk_api_public_document_v1",
    "edge_eligible_at_t_as_of_unix_ns",
    "extract_evidence_envelope_v1",
    "extract_walk_result_hash_body_v1",
    "exploration_partition_id_v1",
    "list_export_sequence_monotonicity_violations_v1",
    "list_forbidden_cognition_key_violations",
    "list_fs_api01_sync_request_json_cap_violations_v1",
    "list_fs_api01_sync_response_json_cap_violations_v1",
    "list_fs_di01_derived_edge_lineage_violations",
    "list_fs_irj02_incomplete_node_set_compare_violations_v1",
    "list_fs_di03_index_epoch_regression_violations",
    "list_fs_ibj02_duplicate_committed_epoch_different_hash_violations",
    "list_rule_ibj01_simultaneous_building_lease_violations",
    "list_fs_mg01_duplicate_fingerprint_violations",
    "list_fs_rem01_reference_walk_artifact_forbidden_keys_v1",
    "list_fs_wr03_duplicate_hop_sequence_violations",
    "list_fs_wes03_forbidden_optimization_keys_under_hash_body_v1",
    "list_fs_te01_same_inputs_different_hash_violations_v1",
    "list_fs_te02_fast_path_without_equiv_pass_violations_v1",
    "list_superseded_link_still_present_violations_v1",
    "list_octs_doctrine_gate_ids_v1",
    "list_octs_gate_catalog_entries_v1",
    "list_oct_graph_import_violations",
    "list_oct_traversal_ingress_token_violations",
    "list_walk_policy_sync_cap_violations_v1",
    "list_walk_result_hash_body_unknown_keys_v1",
    "list_wired_verification_runners_v1",
    "list_wr02_forbidden_key_violations_under_hash_body",
    "neighbor_expansion_fingerprints_ordered_v1",
    "org_link_eligible_half_open_unix_ns_v1",
    "path_context_id_v1",
    "linearized_export_sequence_commits_v1",
    "recomputed_edge_fingerprint_from_receipt_v1",
    "run_octs_pr_blocking_static_stages_v1",
    "run_octs_wired_verification_stages_v1",
    "run_reference_frontier_walk_v1",
    "load_verification_waivers_v1",
    "load_oct_derived_index_replay_verify_v1_schema",
    "load_oct_walk_request_v1_schema",
    "oct_walk_policy_v1_schema_path",
    "oct_derived_index_replay_verify_v1_schema_path",
    "oct_walk_request_minimal_fixture_path",
    "prepare_effective_oct_walk_request_v1",
    "resolve_oct_engine_build_id_v1",
    "octs_derived_index_fixture_dir",
    "octs_economics_golden_dir_v1",
    "octs_exploration_fixture_dir",
    "octs_golden_vectors_v1_root",
    "octs_golden_vectors_v1_root_for_tenant_slice",
    "octs_hop_receipt_fixture_dir",
    "octs_index_build_job_fixture_dir",
    "octs_walk_diagnostics_fixture_dir",
    "octs_walk_execution_strategy_fixture_dir",
    "octs_walk_policy_fixture_dir",
    "octs_walk_result_fixture_dir",
    "octs_multigraph_neighbor_order_fixture_dir",
    "octs_runtime_execution_fixture_dir",
    "octs_temporal_fixture_dir",
    "octs_org_graph_traversal_verification_slice_schema_path",
    "octs_tenant_verification_slice_enabled_v1",
    "octs_control_plane_show_exploration_v1",
    "octs_walk_api_openapi_path",
    "octs_walk_api_memory_store_v1",
    "oct_walk_request_v1_schema_path",
    "octs_walk_diagnostics_enums_schema_path",
    "WALK_EXECUTION_STRATEGY_HYBRID_PINNED",
    "WALK_EXECUTION_STRATEGY_MATERIALIZED_DERIVED",
    "WALK_EXECUTION_STRATEGY_ONLINE_OBSERVED",
    "ObservedDerivedInvariantError",
    "OctsEngineIdentityError",
    "OctsGateCatalogEntryV1",
    "OTEL_EXPLORATION_SINK_NAME",
    "validate_octs_canonical_json_mapping_no_cognition_leakage",
    "verification_waivers_yaml_path",
    "default_severity_for_gate_v1",
    "gate_stage_v1",
    "verify_oct_verification_gates_step22_static_bundle",
    "verify_octs_corruption_bundles_reference_known_gates_static",
    "verify_octs_gate_catalog_unique_ids_static",
    "verify_octs_readiness_economics_receipt_v1_shape",
    "verify_octs_waiver_entries_schema_static",
    "verify_octs_waiver_yaml_parseable_static",
    "verify_octs_wired_runner_gate_ids_match_static",
    "validate_hop_receipt_observed_derived",
    "validate_hop_receipt_list_contract_v1",
    "validate_hop_receipt_list_for_hash_body_v1",
    "validate_hop_receipt_sequence",
    "validate_hybrid_policy_integer_threshold_for_strategy_v1",
    "validate_skip_reason_enum_v1",
    "validate_stale_derived_read_policy_v1",
    "validate_termination_reason_enum_v1",
    "validate_inner_projection_matches_stable_hash",
    "validate_materialized_adjacency_hop_receipt_v1",
    "validate_index_build_completion_events_v1",
    "validate_index_build_job_receipt_v1",
    "validate_index_build_job_state_sequence_v1",
    "validate_index_build_job_state_transition_v1",
    "validate_oct_traversal_import_projection",
    "validate_oct_derived_index_replay_verify_body_v1",
    "validate_org_graph_traversal_verification_slice_v1",
    "validate_octs_traversal_control_plane_v1_shape",
    "validate_oct_walk_policy_v1_jsonschema",
    "validate_oct_walk_request_v1",
    "validate_publish_barrier_record_v1",
    "validate_graph_as_of_vs_snapshot_clock_skew_v1",
    "validate_derived_index_artifact_contract_v1",
    "validate_fs_ibj03_shadow_store_visibility_v1",
    "validate_fs_wes01_materialized_requires_pinned_index_epoch_v1",
    "validate_execution_partition_enum_v1",
    "validate_exploration_hash_body_invariants_v1",
    "validate_fast_path_equivalence_record_v1",
    "validate_temporal_anchor_has_projection_content_hash",
    "validate_temporal_anchor_invariants_v1",
    "validate_temporal_anchor_extension_sorted_keys_v1",
    "validate_walk_observed_derived_consistency",
    "validate_walk_policy_for_request_v1",
    "validate_walk_result_hash_body_contract_v1",
    "validate_walk_diagnostics_hash_body_contract_v1",
    "validate_walk_result_hash_body_tvr_strict_v1",
    "validate_row_destination_exploration_law_v1",
    "temporal_anchor_canonical_json_bytes_v1",
    "walk_policy_canonical_json_bytes_for_hash_v1",
    "verify_gp05_api01_openapi_walk_paths_static",
    "verify_gp05_api02_openapi_security_static",
    "verify_gp05_api03_sync_walk_limits_static",
    "verify_gp05_replay_idx01_double_run_equality_static",
    "verify_gp05_replay_idx02_corrupt_lineage_deterministic_failure_static",
    "verify_oct_traversal_equivalence_step21_static_bundle",
    "verify_oct_walk_replay_stub_inherit_resolution_static",
    "verify_gp05_ovd01_observed_hop_bindings_static",
    "verify_gp05_ovd02_strategy_and_derived_flags_static",
    "verify_gp05_anti01_forbidden_cognition_keys_static",
    "verify_gp05_anti02_traversal_ingress_no_phase03_tokens_static",
    "verify_gp05_diag01_enum_exhaustiveness_vs_schema_static",
    "verify_gp05_diag02_cycle_fingerprint_golden_static",
    "verify_gp05_eng01_engine_build_id_coherence_static",
    "verify_gp05_equiv01_fast_path_online_equivalence_static",
    "verify_gp05_idx01_index_content_hash_stability_static",
    "verify_gp05_idx02_lineage_completeness_static",
    "verify_gp05_job01_index_build_fsm_illegal_transitions_static",
    "verify_gp05_job02_validating_publish_audit_static",
    "verify_leq01_walk_hash_double_run_stub_static",
    "verify_leq02_async_job_order_independence_stub_static",
    "verify_leq03_fast_path_equiv_obligation_static",
    "verify_gp05_exp01_walk_request_explicit_exploration_mode_static",
    "verify_gp05_exp02_authoritative_table_rejects_exploration_partition_static",
    "verify_gp05_import01_traversable_subset_authoritative_static",
    "verify_gp05_import02_forbidden_ingress_tokens_static",
    "verify_gp05_mg01_neighbor_order_golden_static",
    "verify_gp05_mg02_fingerprint_uniqueness_static",
    "verify_gp05_temp01_sequence_validity_supersession_static",
    "verify_gp05_temp02_anchor_roundtrip_and_concurrency_static",
    "verify_gp05_pol01_walk_policy_schema_and_hash_static",
    "verify_gp05_pol02_sync_caps_reject_static",
    "verify_gp05_rt01_engine_determinism_static",
    "verify_gp05_rt02_frontier_cap_budget_static",
    "verify_gp05_hash01_walk_result_hash_recompute_static",
    "verify_gp05_hash02_telemetry_separation_static",
    "verify_gp05_hr01_fingerprint_recompute_from_envelope_static",
    "verify_gp05_hr02_dangling_org_link_rejected_static",
    "verify_gp05_schema01_oct_walk_request_v1_static",
    "verify_gp05_tvr01_walk_result_hash_body_strict_static",
    "verify_gp05_tver01_org_graph_traversal_slice_golden_static",
    "verify_gp05_cp01_traversal_control_plane_rbac_static",
    "verify_gp05_eco01_max_out_degree_golden_static",
    "verify_gp05_eco02_walk_wall_budget_golden_static",
    "verify_gp05_eco03_derived_index_bytes_per_edge_golden_static",
    "verify_gp05_wes01_strategy_affects_policy_hash_static",
    "verify_gp05_wes03_forbidden_optimization_hash_body_scan_static",
]
