/** Must match backend ``HARD_DELETE_TENANT_CONFIRMATION_PHRASE`` exactly. */
export const HARD_DELETE_TENANT_CONFIRMATION_PHRASE = "DELETE TENANT AND ALL DATA";

/** Must match backend ``RESET_TENANT_TO_SIGNUP_CONFIRMATION_PHRASE`` exactly. */
export const RESET_TENANT_TO_SIGNUP_CONFIRMATION_PHRASE = "RESET WORKSPACE TO FRESH SIGNUP";

/** Must match backend ``HARD_DELETE_ORPHAN_USER_CONFIRMATION_PHRASE`` exactly. */
export const HARD_DELETE_ORPHAN_USER_CONFIRMATION_PHRASE = "DELETE USER ACCOUNT";

/** Phase 01 Step 6 — must match backend ``CORTEX_MANUAL_SYNC_CONFIRM_PHRASE``. */
export const CORTEX_MANUAL_SYNC_CONFIRM_PHRASE = "RUN MANUAL CORTEX INGESTION SYNC";

/** Phase 01 Step 6 — must match backend ``CORTEX_REPLAY_CONFIRM_PHRASE``. */
export const CORTEX_REPLAY_CONFIRM_PHRASE = "RUN CORTEX INGESTION REPLAY JOB";

/** Must match backend ``CORTEX_FLUSH_RERUN_CONFIRM_PHRASE``. */
export const CORTEX_FLUSH_RERUN_CONFIRM_PHRASE = "FLUSH RAW DATA AND RERUN CORTEX THROUGH PHASE 07";

/** Phase 01 Step 6 — must match backend ``CORTEX_SCHEDULER_PAUSE_CONFIRM_PHRASE``. */
export const CORTEX_SCHEDULER_PAUSE_CONFIRM_PHRASE = "PAUSE ALL SCHEDULED CORTEX INGESTION";

/** Phase 01 Step 6 — must match backend ``CORTEX_SCHEDULER_RESUME_CONFIRM_PHRASE``. */
export const CORTEX_SCHEDULER_RESUME_CONFIRM_PHRASE = "RESUME ALL SCHEDULED CORTEX INGESTION";

/** Phase 07 Step 24 — must match backend ``RETRIEVAL_INDEX_REBUILD_CONFIRM_PHRASE_V1``. */
export const RETRIEVAL_INDEX_REBUILD_CONFIRM_PHRASE = "EXECUTE RETRIEVAL INDEX REBUILD";
