/** Must match backend ``HARD_DELETE_TENANT_CONFIRMATION_PHRASE`` exactly. */
export const HARD_DELETE_TENANT_CONFIRMATION_PHRASE = "DELETE TENANT AND ALL DATA";

/** Must match backend ``RESET_TENANT_TO_SIGNUP_CONFIRMATION_PHRASE`` exactly. */
export const RESET_TENANT_TO_SIGNUP_CONFIRMATION_PHRASE = "RESET WORKSPACE TO FRESH SIGNUP";

/** Must match backend ``HARD_DELETE_ORPHAN_USER_CONFIRMATION_PHRASE`` exactly. */
export const HARD_DELETE_ORPHAN_USER_CONFIRMATION_PHRASE = "DELETE USER ACCOUNT";

/** Phase 01 Step 6 — must match backend ``CORTEX_MANUAL_SYNC_CONFIRM_PHRASE``. */
export const CORTEX_MANUAL_SYNC_CONFIRM_PHRASE = "RUN MANUAL CORTEX INGESTION SYNC";

/** Phase 01 Step 6 — must match backend ``CORTEX_REPLAY_CONFIRM_PHRASE``. */
export const CORTEX_REPLAY_CONFIRM_PHRASE = "RUN CORTEX INGESTION REPLAY JOB";

/** Must match backend ``CORTEX_FLUSH_RERUN_CONFIRM_PHRASE``. */
export const CORTEX_FLUSH_RERUN_CONFIRM_PHRASE = "FLUSH RAW DATA AND RERUN CORTEX THROUGH PHASE 07";

/** Admin revamp — flush derived substrate only (operator UI). */
export const CORTEX_FLUSH_DERIVED_CONFIRM_PHRASE = "FLUSH DERIVED CORTEX DATA AND RERUN FROM CANONICAL";

/** Phase 01 Step 6 — must match backend ``CORTEX_SCHEDULER_PAUSE_CONFIRM_PHRASE``. */
export const CORTEX_SCHEDULER_PAUSE_CONFIRM_PHRASE = "PAUSE ALL SCHEDULED CORTEX INGESTION";

/** Phase 01 Step 6 — must match backend ``CORTEX_SCHEDULER_RESUME_CONFIRM_PHRASE``. */
export const CORTEX_SCHEDULER_RESUME_CONFIRM_PHRASE = "RESUME ALL SCHEDULED CORTEX INGESTION";

/** Phase 07 Step 24 — must match backend ``RETRIEVAL_INDEX_REBUILD_CONFIRM_PHRASE_V1``. */
export const RETRIEVAL_INDEX_REBUILD_CONFIRM_PHRASE = "EXECUTE RETRIEVAL INDEX REBUILD";

/** R2 operator actions — must match backend ``CORTEX_RESTART_EXECUTION_CONFIRM_PHRASE``. */
export const CORTEX_RESTART_EXECUTION_CONFIRM_PHRASE = "RESTART CORTEX EXECUTION FROM PHASE";

/** R2 operator actions — must match backend ``CORTEX_CLEAR_DERIVED_CONFIRM_PHRASE``. */
export const CORTEX_CLEAR_DERIVED_CONFIRM_PHRASE = "CLEAR DERIVED CORTEX EXECUTION OUTPUTS";

/** R2 operator actions — must match backend ``REBUILD_IDENTITIES_CONFIRM_PHRASE``. */
export const REBUILD_IDENTITIES_CONFIRM_PHRASE = "REBUILD IDENTITIES FROM CANONICAL ANCHORS";

/** R2 operator actions — must match backend ``CONTINUITY_P0_RECOVER_CONFIRM_PHRASE``. */
export const CONTINUITY_P0_RECOVER_CONFIRM_PHRASE = "RECOVER CONTINUITY P0 PIPELINE";
