/** Must match backend ``HARD_DELETE_TENANT_CONFIRMATION_PHRASE`` exactly. */
export const HARD_DELETE_TENANT_CONFIRMATION_PHRASE = "DELETE TENANT AND ALL DATA";

/** Must match backend ``RESET_TENANT_TO_SIGNUP_CONFIRMATION_PHRASE`` exactly. */
export const RESET_TENANT_TO_SIGNUP_CONFIRMATION_PHRASE = "RESET WORKSPACE TO FRESH SIGNUP";

/** Must match backend ``HARD_DELETE_ORPHAN_USER_CONFIRMATION_PHRASE`` exactly. */
export const HARD_DELETE_ORPHAN_USER_CONFIRMATION_PHRASE = "DELETE USER ACCOUNT";
