"""Phase 08 — Synthesis & Intelligence Layer (SIL).

P08-01: ``normative.PHASE08_PROGRAM_FREEZE_VERSION`` + ``build_phase08_normative_program_document_v1``
(``phase-08-normative-index.md``).
P08-02: ``anti_goals`` — forbidden cognition keys + ``G-P08-ANTI-01`` / ``G-P08-ANTI-02`` gates
(``phase-08-anti-goals-doctrine.md``).
P08-03: ``phase_boundaries`` — SYN-BND-07/09/10 + ``validate_synthesis_ingress_from_retrieval_v1``
(``phase-08-phase-boundaries-doctrine.md``).
P08-04: ``synthesis_ingress`` — ``RetrievalEvidenceIngressV1`` + **SYN-INGRESS-*** gates
(``phase-08-data-contracts.md`` §Ingress).
P08-05: ``synthesis_job_contract`` — 8 workloads + 5 intents + **G-P08-SCHEMA-01**
(``phase-08-data-contracts.md`` §1–2).
P08-06: ``synthesis_job_envelope`` + ``synthesis_orchestrator`` — 9-phase FSM skeleton
(``phase-08-synthesis-law-system.md`` §FSM).
P08-07: ``synthesis_legality_matrix`` — **S-LEG-01..07** + **G-P08-LEG-01**
(``phase-08-synthesis-law-system.md`` §Legality).
P08-08: ``synthesis_replay_equivalence`` — **G-P08-REPLAY-01**, **SYN-REP-01** replay identity + receipt law
(``phase-08-replay-equivalence-spec.md``).
P08-09: ``synthesis_evidence_binding`` — **G-P08-CITE-01**, **SYN-LAW-09** cite-or-omit + ``SynthesisCitationV1``
(``phase-08-data-contracts.md`` §Citations).
P08-10: ``synthesis_query_plan`` — **G-P08-RETRIEVE-01** PLAN+RETRIEVE via Phase **07** only
(``phase-08-synthesis-runtime-architecture.md`` §Orchestrator).
P08-11: ``synthesis_llm_router`` + ``adapters.llm`` — **G-P08-LLM-01** model routes + **FakeLlmAdapter**
(``phase-08-synthesis-law-system.md`` §AI).
P08-12: ``synthesis_prompt_assembly`` — **G-P08-PRM-01** template registry + **SYN-PRM-01..04** prompt pins
(``phase-08-synthesis-law-system.md`` §Prompts).
"""

from vector.domains.cortex.synthesis.anti_goals import (
    PHASE08_ANTI_GOALS_RUNTIME_SCHEMA_VERSION,
    SYNTHESIS_ARTIFACT_FORBIDDEN_TOP_LEVEL_KEYS_LOWER_V1,
    SYNTHESIS_FORBIDDEN_LEGALITY_CLASS_V1,
    SYNTHESIS_JOB_ENVELOPE_FORBIDDEN_KEYS_LOWER_V1,
    SynthesisAntiGoalViolationError,
    SynthesisCognitionLeakageError,
    build_synthesis_anti_goals_doctrine_catalog_v1,
    enforce_synthesis_job_envelope_anti_goals_v1,
    verify_gp08_anti01_synthesis_package_static,
    verify_gp08_anti02_synthesis_ingress_token_rejection_static,
)
from vector.domains.cortex.synthesis.phase_boundaries import (
    PHASE08_BOUNDARIES_RUNTIME_SCHEMA_VERSION,
    SD_PIPELINE_GAP_V1,
    SD_UPSTREAM_LEG_V1,
    SD_UPSTREAM_RD_V1,
    SYN_BND_RULE_IDS_V1,
    SynthesisPhaseBoundaryError,
    build_synthesis_phase_boundary_catalog_v1,
    enforce_synthesis_job_retrieval_boundary_v1,
    propagate_retrieval_omissions_to_sd_rows_v1,
    validate_synthesis_ingress_from_retrieval_v1,
    verify_gp08_bnd07_retrieval_ingress_static,
    verify_gp08_bnd09_products_boundary_static,
    verify_gp08_bnd_acyclic_dependency_static,
)
from vector.domains.cortex.synthesis.synthesis_ingress import (
    GP08_INGRESS01_GATE_ID_V1,
    PHASE08_INGRESS_RUNTIME_SCHEMA_VERSION,
    RETRIEVAL_EVIDENCE_INGRESS_SCHEMA_VERSION,
    SYN_INGRESS_GATE_IDS_V1,
    SynthesisIngressError,
    build_retrieval_evidence_ingress_v1,
    build_synthesis_ingress_inspector_v1,
    build_synthesis_ingress_law_catalog_v1,
    compute_retrieval_ingress_digest_v1,
    enforce_retrieval_evidence_ingress_v1,
    validate_retrieval_evidence_ingress_v1,
    verify_gp08_ingress01_retrieval_evidence_ingress_static,
)
from vector.domains.cortex.synthesis.synthesis_job_envelope import (
    PHASE08_SYNTHESIS_JOB_ENVELOPE_RUNTIME_SCHEMA_VERSION,
    SynthesisJobEnvelopeError,
    coerce_body_to_synthesis_job_envelope_v1,
    compute_synthesis_job_envelope_digest_v1,
    normalize_synthesis_job_envelope_v1,
    synthesis_policy_pack_digest_v1,
)
from vector.domains.cortex.synthesis.synthesis_llm_router import (
    GP08_LLM01_GATE_ID_V1,
    PHASE08_SYNTHESIS_LLM_ROUTER_RUNTIME_SCHEMA_VERSION,
    SynthesisLlmRouterError,
    build_synthesis_llm_model_route_catalog_v1,
    build_synthesis_llm_route_preview_v1,
    execute_synthesis_llm_phase_v1,
    verify_gp08_llm01_fake_adapter_determinism_static,
    verify_gp08_llm01_model_route_registry_static,
    verify_gp08_llm01_retrieval_legality_gate_static,
    verify_gp08_llm01_sd_mapping_static,
)
from vector.domains.cortex.synthesis.synthesis_prompt_assembly import (
    GP08_PRM01_GATE_ID_V1,
    PHASE08_SYNTHESIS_PROMPT_ASSEMBLY_RUNTIME_SCHEMA_VERSION,
    SynthesisPromptAssemblyError,
    assemble_synthesis_prompts_for_job_v1,
    build_synthesis_prompt_assembly_preview_v1,
    build_synthesis_prompt_context_v1,
    build_synthesis_prompt_template_catalog_v1,
    compute_synthesis_prompt_hash_v1,
    verify_gp08_prm01_context_required_fields_static,
    verify_gp08_prm01_prompt_hash_stable_static,
    verify_gp08_prm01_template_registry_static,
    verify_gp08_prm01_variant_override_law_static,
)
from vector.domains.cortex.synthesis.synthesis_query_plan import (
    GP08_RETRIEVE01_GATE_ID_V1,
    PHASE08_SYNTHESIS_QUERY_PLAN_RUNTIME_SCHEMA_VERSION,
    SD_CAP_RETRIEVAL_V1,
    SynthesisQueryPlanError,
    build_retrieval_query_envelope_for_plan_item_v1,
    build_synthesis_retrieval_plan_catalog_v1,
    build_synthesis_retrieval_plan_preview_v1,
    build_synthesis_retrieval_plan_v1,
    execute_synthesis_retrieval_plan_v1,
    merge_retrieval_responses_v1,
    verify_gp08_retrieve01_merge_responses_static,
    verify_gp08_retrieve01_plan_fanout_static,
    verify_gp08_retrieve01_query_envelope_static,
)
from vector.domains.cortex.synthesis.synthesis_evidence_binding import (
    GP08_CITE01_GATE_ID_V1,
    PHASE08_SYNTHESIS_EVIDENCE_BINDING_RUNTIME_SCHEMA_VERSION,
    SYN_LAW_09_RULE_ID_V1,
    SynthesisEvidenceBindingError,
    apply_syn_law_09_cite_or_omit_v1,
    bind_synthesis_evidence_v1,
    build_synthesis_citation_binding_inspector_v1,
    build_synthesis_citation_envelope_v1,
    build_synthesis_citation_law_catalog_v1,
    build_synthesis_citation_v1,
    build_synthesis_citations_from_hits_v1,
    verify_gp08_cite01_citation_schema_static,
    verify_gp08_cite01_cite_or_omit_static,
    verify_gp08_cite01_envelope_digest_stable_static,
)
from vector.domains.cortex.synthesis.synthesis_replay_equivalence import (
    GP08_REPLAY_01_GATE_ID_V1,
    GP08_REPLAY_02_GATE_ID_V1,
    PHASE08_SYNTHESIS_REPLAY_EQUIVALENCE_RUNTIME_SCHEMA_VERSION,
    SYN_REP_01_RULE_ID_V1,
    SynthesisReplayEquivalenceError,
    build_synthesis_job_receipt_v1,
    build_synthesis_job_replay_inspector_v1,
    build_synthesis_replay_equivalence_twin_diff_v1,
    build_synthesis_replay_explorer_catalog_v1,
    compare_gp08_replay_01_double_run_v1,
    compute_synthesis_job_replay_identity_v1,
    enforce_synthesis_expected_replay_identity_v1,
    verify_gp08_replay01_canonical_identity_stable_static,
    verify_gp08_replay01_double_run_match_static,
    verify_gp08_replay01_receipt_embed_law_static,
)
from vector.domains.cortex.synthesis.synthesis_orchestrator import (
    GP08_FSM01_GATE_ID_V1,
    PHASE08_SYNTHESIS_ORCHESTRATOR_RUNTIME_SCHEMA_VERSION,
    SYNTHESIS_JOB_EXECUTION_PHASES_V1,
    SYNTHESIS_JOB_RECEIPT_SCHEMA_VERSION_V1,
    SYNTHESIS_ORCHESTRATOR_BUILD_ID_V1,
    SynthesisOrchestratorError,
    execute_synthesis_job_envelope_v1,
    get_synthesis_job_detail_v1,
    verify_gp08_fsm01_synthesis_phase_order_static,
    verify_gp08_schema01_synthesis_job_envelope_execution_static,
)
from vector.domains.cortex.synthesis.synthesis_repository import (
    create_synthesis_job_row_v1,
    find_idempotent_synthesis_job_v1,
    persist_synthesis_job_receipt_row_v1,
)
from vector.domains.cortex.synthesis.synthesis_legality_matrix import (
    GP08_LEG01_GATE_ID_V1,
    PHASE08_SYNTHESIS_LEGALITY_MATRIX_RUNTIME_SCHEMA_VERSION,
    SYNTHESIS_LEGALITY_CLASSES_V1,
    SYNTHESIS_LEGALITY_CLASS_ORDINALS_V1,
    SynthesisLegalityError,
    aggregate_synthesis_legality_class_v1,
    assert_synthesis_job_lawful_v1,
    build_synthesis_jobs_by_legality_histogram_v1,
    build_synthesis_legality_matrix_catalog_v1,
    build_synthesis_legality_posture_v1,
    classify_synthesis_legality_for_job_v1,
    max_synthesis_legality_class_v1,
    verify_gp08_leg01_synthesis_legality_matrix_static,
)
from vector.domains.cortex.synthesis.synthesis_job_contract import (
    DEFAULT_SYNTHESIS_POLICY_PACK_ID_V1,
    GP08_SCHEMA01_WORKLOAD_INTENT_GATE_ID_V1,
    PHASE08_SYNTHESIS_JOB_CONTRACT_RUNTIME_SCHEMA_VERSION,
    SYNTHESIS_INTENT_CLASSES_V1,
    SYNTHESIS_JOB_ENVELOPE_SCHEMA_VERSION_V1,
    SYNTHESIS_WORKLOAD_CLASSES_V1,
    SynthesisJobContractError,
    build_synthesis_intent_class_catalog_v1,
    build_synthesis_job_contract_catalog_v1,
    build_synthesis_job_replay_identity_scope_v1,
    build_synthesis_workload_class_catalog_v1,
    enforce_synthesis_job_workload_and_intent_v1,
    resolve_synthesis_workload_and_intent_v1,
    selection_policy_caps_for_synthesis_workload_v1,
    validate_synthesis_intent_v1,
    validate_synthesis_workload_class_v1,
    verify_gp08_schema01_synthesis_workload_intent_registry_static,
)
from vector.domains.cortex.synthesis.doctrine_catalog import (
    SYNTHESIS_PROGRAM_CATALOG_RUNTIME_SCHEMA_VERSION,
    build_synthesis_program_doctrine_catalog_v1,
)
from vector.domains.cortex.synthesis.normative import (
    PHASE08_DEGRADATION_TAXONOMY_SPEC_REF_V1,
    PHASE08_FREEZE_BUNDLE_IDS,
    PHASE08_NORMATIVE_TREE_V1,
    PHASE08_POLICY_PACK_FIXTURE_REF_V1,
    PHASE08_PROGRAM_FREEZE_VERSION,
    PHASE08_REPLAY_IDENTITY_FIELD_V1,
    PHASE08_REPLAY_SPEC_REF_V1,
    PHASE08_RUNTIME_PACKAGE_V1,
    PHASE08_STEP_PROGRAM_COUNT,
    PHASE08_SUBSTRATE_PIPELINE_STAGES_V1,
    PHASE08_UPSTREAM_REPLAY_IDENTITY_FIELD_V1,
    build_phase08_normative_program_document_v1,
)

__all__ = [
    "PHASE08_ANTI_GOALS_RUNTIME_SCHEMA_VERSION",
    "PHASE08_BOUNDARIES_RUNTIME_SCHEMA_VERSION",
    "PHASE08_DEGRADATION_TAXONOMY_SPEC_REF_V1",
    "PHASE08_INGRESS_RUNTIME_SCHEMA_VERSION",
    "PHASE08_SYNTHESIS_JOB_CONTRACT_RUNTIME_SCHEMA_VERSION",
    "PHASE08_SYNTHESIS_JOB_ENVELOPE_RUNTIME_SCHEMA_VERSION",
    "PHASE08_SYNTHESIS_LEGALITY_MATRIX_RUNTIME_SCHEMA_VERSION",
    "PHASE08_SYNTHESIS_ORCHESTRATOR_RUNTIME_SCHEMA_VERSION",
    "PHASE08_FREEZE_BUNDLE_IDS",
    "PHASE08_NORMATIVE_TREE_V1",
    "PHASE08_POLICY_PACK_FIXTURE_REF_V1",
    "PHASE08_PROGRAM_FREEZE_VERSION",
    "PHASE08_REPLAY_IDENTITY_FIELD_V1",
    "PHASE08_REPLAY_SPEC_REF_V1",
    "PHASE08_RUNTIME_PACKAGE_V1",
    "PHASE08_STEP_PROGRAM_COUNT",
    "PHASE08_SUBSTRATE_PIPELINE_STAGES_V1",
    "PHASE08_UPSTREAM_REPLAY_IDENTITY_FIELD_V1",
    "DEFAULT_SYNTHESIS_POLICY_PACK_ID_V1",
    "GP08_INGRESS01_GATE_ID_V1",
    "GP08_FSM01_GATE_ID_V1",
    "GP08_LEG01_GATE_ID_V1",
    "GP08_CITE01_GATE_ID_V1",
    "GP08_RETRIEVE01_GATE_ID_V1",
    "GP08_LLM01_GATE_ID_V1",
    "GP08_PRM01_GATE_ID_V1",
    "GP08_REPLAY_01_GATE_ID_V1",
    "GP08_REPLAY_02_GATE_ID_V1",
    "GP08_SCHEMA01_WORKLOAD_INTENT_GATE_ID_V1",
    "PHASE08_SYNTHESIS_EVIDENCE_BINDING_RUNTIME_SCHEMA_VERSION",
    "PHASE08_SYNTHESIS_QUERY_PLAN_RUNTIME_SCHEMA_VERSION",
    "PHASE08_SYNTHESIS_LLM_ROUTER_RUNTIME_SCHEMA_VERSION",
    "PHASE08_SYNTHESIS_PROMPT_ASSEMBLY_RUNTIME_SCHEMA_VERSION",
    "PHASE08_SYNTHESIS_REPLAY_EQUIVALENCE_RUNTIME_SCHEMA_VERSION",
    "SD_CAP_RETRIEVAL_V1",
    "SYN_LAW_09_RULE_ID_V1",
    "SYN_REP_01_RULE_ID_V1",
    "RETRIEVAL_EVIDENCE_INGRESS_SCHEMA_VERSION",
    "SD_PIPELINE_GAP_V1",
    "SD_UPSTREAM_LEG_V1",
    "SD_UPSTREAM_RD_V1",
    "SYN_BND_RULE_IDS_V1",
    "SYN_INGRESS_GATE_IDS_V1",
    "SYNTHESIS_INTENT_CLASSES_V1",
    "SYNTHESIS_LEGALITY_CLASSES_V1",
    "SYNTHESIS_LEGALITY_CLASS_ORDINALS_V1",
    "SYNTHESIS_JOB_ENVELOPE_SCHEMA_VERSION_V1",
    "SYNTHESIS_JOB_EXECUTION_PHASES_V1",
    "SYNTHESIS_JOB_RECEIPT_SCHEMA_VERSION_V1",
    "SYNTHESIS_ORCHESTRATOR_BUILD_ID_V1",
    "SYNTHESIS_WORKLOAD_CLASSES_V1",
    "SYNTHESIS_ARTIFACT_FORBIDDEN_TOP_LEVEL_KEYS_LOWER_V1",
    "SYNTHESIS_FORBIDDEN_LEGALITY_CLASS_V1",
    "SYNTHESIS_JOB_ENVELOPE_FORBIDDEN_KEYS_LOWER_V1",
    "SYNTHESIS_PROGRAM_CATALOG_RUNTIME_SCHEMA_VERSION",
    "SynthesisAntiGoalViolationError",
    "SynthesisCognitionLeakageError",
    "SynthesisIngressError",
    "SynthesisJobContractError",
    "SynthesisJobEnvelopeError",
    "SynthesisLegalityError",
    "SynthesisOrchestratorError",
    "SynthesisPhaseBoundaryError",
    "SynthesisEvidenceBindingError",
    "SynthesisQueryPlanError",
    "SynthesisLlmRouterError",
    "SynthesisPromptAssemblyError",
    "SynthesisReplayEquivalenceError",
    "build_phase08_normative_program_document_v1",
    "build_retrieval_evidence_ingress_v1",
    "build_synthesis_anti_goals_doctrine_catalog_v1",
    "build_synthesis_intent_class_catalog_v1",
    "build_synthesis_ingress_inspector_v1",
    "aggregate_synthesis_legality_class_v1",
    "assert_synthesis_job_lawful_v1",
    "build_synthesis_job_contract_catalog_v1",
    "build_synthesis_jobs_by_legality_histogram_v1",
    "build_synthesis_legality_matrix_catalog_v1",
    "build_synthesis_legality_posture_v1",
    "classify_synthesis_legality_for_job_v1",
    "apply_syn_law_09_cite_or_omit_v1",
    "bind_synthesis_evidence_v1",
    "build_synthesis_citation_binding_inspector_v1",
    "build_synthesis_citation_envelope_v1",
    "build_synthesis_citation_law_catalog_v1",
    "build_synthesis_citation_v1",
    "build_synthesis_citations_from_hits_v1",
    "build_synthesis_job_receipt_v1",
    "build_synthesis_job_replay_inspector_v1",
    "build_synthesis_replay_equivalence_twin_diff_v1",
    "build_synthesis_replay_explorer_catalog_v1",
    "build_retrieval_query_envelope_for_plan_item_v1",
    "build_synthesis_llm_model_route_catalog_v1",
    "build_synthesis_llm_route_preview_v1",
    "execute_synthesis_llm_phase_v1",
    "assemble_synthesis_prompts_for_job_v1",
    "build_synthesis_prompt_assembly_preview_v1",
    "build_synthesis_prompt_context_v1",
    "build_synthesis_prompt_template_catalog_v1",
    "compute_synthesis_prompt_hash_v1",
    "build_synthesis_retrieval_plan_catalog_v1",
    "build_synthesis_retrieval_plan_preview_v1",
    "build_synthesis_retrieval_plan_v1",
    "compare_gp08_replay_01_double_run_v1",
    "execute_synthesis_retrieval_plan_v1",
    "merge_retrieval_responses_v1",
    "compute_synthesis_job_replay_identity_v1",
    "enforce_synthesis_expected_replay_identity_v1",
    "build_synthesis_job_replay_identity_scope_v1",
    "build_synthesis_workload_class_catalog_v1",
    "build_synthesis_ingress_law_catalog_v1",
    "build_synthesis_phase_boundary_catalog_v1",
    "build_synthesis_program_doctrine_catalog_v1",
    "compute_retrieval_ingress_digest_v1",
    "enforce_retrieval_evidence_ingress_v1",
    "coerce_body_to_synthesis_job_envelope_v1",
    "compute_synthesis_job_envelope_digest_v1",
    "create_synthesis_job_row_v1",
    "enforce_synthesis_job_workload_and_intent_v1",
    "execute_synthesis_job_envelope_v1",
    "enforce_synthesis_job_envelope_anti_goals_v1",
    "enforce_synthesis_job_retrieval_boundary_v1",
    "propagate_retrieval_omissions_to_sd_rows_v1",
    "get_synthesis_job_detail_v1",
    "max_synthesis_legality_class_v1",
    "normalize_synthesis_job_envelope_v1",
    "resolve_synthesis_workload_and_intent_v1",
    "synthesis_policy_pack_digest_v1",
    "selection_policy_caps_for_synthesis_workload_v1",
    "validate_retrieval_evidence_ingress_v1",
    "validate_synthesis_intent_v1",
    "validate_synthesis_workload_class_v1",
    "validate_synthesis_ingress_from_retrieval_v1",
    "verify_gp08_anti01_synthesis_package_static",
    "verify_gp08_anti02_synthesis_ingress_token_rejection_static",
    "verify_gp08_bnd07_retrieval_ingress_static",
    "verify_gp08_bnd09_products_boundary_static",
    "verify_gp08_bnd_acyclic_dependency_static",
    "verify_gp08_ingress01_retrieval_evidence_ingress_static",
    "verify_gp08_fsm01_synthesis_phase_order_static",
    "verify_gp08_leg01_synthesis_legality_matrix_static",
    "verify_gp08_cite01_citation_schema_static",
    "verify_gp08_cite01_cite_or_omit_static",
    "verify_gp08_cite01_envelope_digest_stable_static",
    "verify_gp08_retrieve01_merge_responses_static",
    "verify_gp08_retrieve01_plan_fanout_static",
    "verify_gp08_retrieve01_query_envelope_static",
    "verify_gp08_llm01_fake_adapter_determinism_static",
    "verify_gp08_llm01_model_route_registry_static",
    "verify_gp08_llm01_retrieval_legality_gate_static",
    "verify_gp08_llm01_sd_mapping_static",
    "verify_gp08_prm01_context_required_fields_static",
    "verify_gp08_prm01_prompt_hash_stable_static",
    "verify_gp08_prm01_template_registry_static",
    "verify_gp08_prm01_variant_override_law_static",
    "verify_gp08_replay01_canonical_identity_stable_static",
    "verify_gp08_replay01_double_run_match_static",
    "verify_gp08_replay01_receipt_embed_law_static",
    "verify_gp08_schema01_synthesis_job_envelope_execution_static",
    "verify_gp08_schema01_synthesis_workload_intent_registry_static",
]
