"""Phase 04 — Identity & Linking (organizational continuity layer).

Step 1 (P04-01): normative freeze metadata.
Step 2 (P04-02): topology vs meaning boundary validators.
Step 3 (P04-03): org entity (org handle) registry.
Step 4 (P04-04): org link ledger (authoritative meaning links).
Step 5 (P04-05): candidate vs authoritative linkage (regen hash, promotion policy).
Step 6 (P04-06): merge governance (append-only merge ledger, policies, gates G-P04-01 / MRG-01 / 13).
Step 7 (P04-07): hint / inferred / prohibited link_class + merge-closure gates G-P04-02 / HINT-01.
Step 8 (P04-08): temporal half-open validity + soft revocation surfaces; gates G-P04-TMP-01 / G-P04-11.
Step 9 (P04-09): cross-bundle equivalence declarations; gates G-P04-BNDL-01 / G-P04-03 / G-P04-14.
Step 10 (P04-10): org link continuity replay jobs + L-class receipts; gate G-P04-RPL-01.
Step 11 (P04-11): linkage rule versions (frozen manifests) + candidate batch pins; gate G-P04-RULE-01.
Step 12 (P04-12): execution primitive instances on org entities; gates G-P04-09 / G-P04-PRIM-01.
Step 13 (P04-13): OrgGraphProjectionV1 export + stable hash; gates G-P04-10 / G-P04-EXP-01.
Step 14 (P04-14): org ambiguity / multiplicity records; gates G-P04-AMB-01 / G-P04-12.
Step 15 (P04-15): org verification slice + G-P04-VER-01 + optional ``cortex_org_verification_runs``; ``identity.verification``.
Step 16 (P04-16): org failure registry + remediation ledger + G-P04-19; ``identity.failure_remediation``.
Step 17 (P04-17): identity control-plane aggregate + G-P04-18 / G-P04-21; ``identity.control_plane``.
"""

from vector.domains.cortex.identity.authoritative_writer import (
    AUTHORITATIVE_WRITER_ENGINE_BUILD_REF,
    AUTHORITATIVE_WRITER_SCHEMA_VERSION,
    PromotionInvariantError,
    create_promotion_policy,
    promote_candidate_to_authoritative_link,
)
from vector.domains.cortex.identity.bundle_equivalence import (
    BUNDLE_EQUIVALENCE_ENGINE_BUILD_REF,
    BUNDLE_EQUIVALENCE_SCHEMA_VERSION,
    BundleEquivalenceError,
    append_bundle_equivalence_declaration,
    bundle_equivalence_public_dict,
    cross_bundle_edge_bundles_from_link_metadata,
    has_active_bundle_equivalence_declaration,
    list_bundle_equivalence_declarations,
    normalize_bundle_pair,
)
from vector.domains.cortex.identity.boundary_checks import (
    BOUNDARY_CHECKS_VERSION,
    TopologyMeaningBoundaryError,
    validate_org_meaning_link_payload,
    verify_topology_meaning_boundary_static,
)
from vector.domains.cortex.identity.execution_primitives import (
    ORG_PRIMITIVE_INSTANCE_ENGINE_BUILD_REF,
    ORG_PRIMITIVE_INSTANCE_SCHEMA_VERSION,
    PrimitivePersistenceError,
    append_org_primitive_instance,
    get_org_primitive_instance,
    list_org_primitive_instances,
    list_org_primitive_instances_missing_evidence,
    org_primitive_instance_public_dict,
    verify_gp04_09_primitive_evidence_discipline_static,
    verify_gp04_prim01_static_evidence_contract,
)
from vector.domains.cortex.identity.candidate_generation import (
    CANDIDATE_GENERATION_ENGINE_BUILD_REF,
    CANDIDATE_GENERATION_SCHEMA_VERSION,
    compute_candidate_set_sha256,
    regenerate_link_candidates,
    verify_authoritative_replay_hash_static,
    verify_candidate_regen_hash_static,
)
from vector.domains.cortex.identity.normative import PHASE04_PROGRAM_FREEZE_VERSION
from vector.domains.cortex.identity.merge_governance import (
    MERGE_GOVERNANCE_ENGINE_BUILD_REF,
    MERGE_GOVERNANCE_SCHEMA_VERSION,
    MergeGovernanceError,
    append_org_merge,
    create_merge_policy,
    list_org_merges,
    merge_public_dict,
    verify_human_merge_two_persona_evidence_policy_static,
    verify_merge_rollback_via_compensating_only_static,
)
from vector.domains.cortex.identity.link_classes import (
    LINK_CLASSES_SCHEMA_VERSION,
    MERGE_CLOSURE_LINK_CLASSES,
    NON_TRUTH_LINK_CLASSES,
    OrgLinkClass,
    normalize_link_class,
    row_eligible_for_merge_closure_material,
    verify_merge_closure_excludes_non_authoritative_link_classes_static,
)
from vector.domains.cortex.identity.linkage_rules import (
    LINK_RULE_VERSION_ENGINE_BUILD_REF,
    LINK_RULE_VERSION_SCHEMA_VERSION,
    LinkageRulesError,
    compute_rules_manifest_sha256,
    create_link_rule_version,
    get_active_link_rule_version_by_semantic,
    get_link_rule_version,
    link_rule_version_public_dict,
    list_link_rule_versions,
    list_candidate_batches_with_rule_version_reference_errors,
    list_link_rule_version_manifest_mismatches,
    verify_link_rule_rule01_static,
)
from vector.domains.cortex.identity.link_ledger import (
    LINK_LEDGER_ENGINE_BUILD_REF,
    LINK_LEDGER_RUNTIME_SCHEMA_VERSION,
    LinkLedgerInvariantError,
    append_non_truth_org_link,
    append_authoritative_org_link,
    assert_authoritative_link_material,
    compute_authoritative_link_set_sha256,
    find_authoritative_temporal_overlaps,
    get_org_link,
    half_open_intervals_overlap,
    link_public_dict,
    list_authoritative_temporal_overlap_violations_for_tenant,
    list_org_link_temporal_timeline,
    list_org_links,
    material_has_evidence_or_rule,
    verify_link_ledger_evidence_rule_static,
)
from vector.domains.cortex.identity.org_link_temporal import (
    ORG_LINK_TEMPORAL_SCHEMA_VERSION,
    OrgLinkTemporalError,
    assert_org_link_validity_half_open,
    org_link_temporal_axis_static_errors,
    org_link_temporal_strip_public,
    verify_link_ledger_soft_revocation_tombstone_static,
)
from vector.domains.cortex.identity.org_link_replay_runtime import (
    ORG_LINK_REPLAY_ENGINE_BUILD_REF,
    ORG_LINK_REPLAY_SCHEMA_VERSION,
    OrgLinkReplayError,
    execute_org_link_replay_job,
    get_org_link_replay_job,
    list_completed_org_link_replay_jobs_missing_receipts,
    list_org_link_replay_jobs,
    org_link_replay_job_public_dict,
    org_link_replay_receipt_public_dict,
    verify_org_link_replay_rpl01_static,
)
from vector.domains.cortex.identity.projection_export import (
    ORG_GRAPH_PROJECTION_ENGINE_BUILD_REF,
    ORG_GRAPH_PROJECTION_SCHEMA_VERSION,
    build_org_graph_projection_export_document,
    build_org_graph_projection_v1,
    org_graph_projection_canonical_json_bytes,
    org_graph_projection_stable_hash_sha256,
    validate_org_graph_projection_v1_shape,
    verify_gp04_10_graph_boundary_export_contract_static,
    verify_gp04_exp01_export_hash_determinism_static,
    verify_org_graph_export_forbidden_leakage,
    verify_org_graph_projection_twice_same_hash,
)
from vector.domains.cortex.identity.org_ambiguity import (
    ORG_AMBIGUITY_CLASSES,
    ORG_AMBIGUITY_ENGINE_BUILD_REF,
    ORG_AMBIGUITY_OPEN_WARN_THRESHOLD,
    ORG_AMBIGUITY_SCHEMA_VERSION,
    ORG_AMBIGUITY_STATUSES,
    OrgAmbiguityError,
    append_org_ambiguity_record,
    count_open_org_ambiguity_records,
    get_org_ambiguity_record,
    list_org_ambiguity_records,
    list_org_ambiguity_records_invalid_entity_refs,
    org_ambiguity_record_public_dict,
    verify_gp04_amb01_org_ambiguity_integrity_static,
)
from vector.domains.cortex.identity.control_plane import (
    IDENTITY_CONTROL_PLANE_CONTRACT,
    IDENTITY_CONTROL_PLANE_RUNTIME_SCHEMA_VERSION,
    build_identity_control_plane,
    verify_gp04_18_org_control_plane_replay_freshness,
    verify_gp04_21_identity_control_plane_aggregate,
    verify_identity_control_plane_v1_shape,
)
from vector.domains.cortex.identity.failure_remediation import (
    ORG_FAILURE_REMEDIATION_RUNTIME_SCHEMA_VERSION,
    org_failure_case_public_dict,
    org_remediation_validation_public_dict,
    recompute_org_derived_failure_cases,
    sync_org_failure_cases,
    validate_org_remediation,
    verify_gp04_19_org_failure_registry_sync,
)
from vector.domains.cortex.identity.verification import (
    ORG_IDENTITY_VERIFICATION_ENGINE_SCHEMA_VERSION,
    PHASE04_NORMATIVE_NUMBERED_GATE_IDS,
    list_org_identity_verification_runs,
    org_verification_run_public_dict,
    run_org_identity_verification,
    verify_gp04_ver01_phase04_catalog_coherence_static,
)
from vector.domains.cortex.identity.org_entities import (
    ORG_ENTITY_ENGINE_BUILD_REF,
    ORG_ENTITY_RUNTIME_SCHEMA_VERSION,
    PHASE04_ORG_ENTITY_NAMESPACE,
    OrgEntityKind,
    deterministic_org_entity_id,
    get_org_entity,
    identity_key_fingerprint,
    list_org_entities,
    org_entity_public_dict,
    upsert_org_entity,
    verify_org_entity_determinism_static,
)

__all__ = [
    "IDENTITY_CONTROL_PLANE_CONTRACT",
    "IDENTITY_CONTROL_PLANE_RUNTIME_SCHEMA_VERSION",
    "ORG_FAILURE_REMEDIATION_RUNTIME_SCHEMA_VERSION",
    "ORG_IDENTITY_VERIFICATION_ENGINE_SCHEMA_VERSION",
    "PHASE04_NORMATIVE_NUMBERED_GATE_IDS",
    "ORG_AMBIGUITY_CLASSES",
    "ORG_AMBIGUITY_ENGINE_BUILD_REF",
    "ORG_AMBIGUITY_OPEN_WARN_THRESHOLD",
    "ORG_AMBIGUITY_SCHEMA_VERSION",
    "ORG_AMBIGUITY_STATUSES",
    "OrgAmbiguityError",
    "ORG_GRAPH_PROJECTION_ENGINE_BUILD_REF",
    "ORG_GRAPH_PROJECTION_SCHEMA_VERSION",
    "ORG_PRIMITIVE_INSTANCE_ENGINE_BUILD_REF",
    "ORG_PRIMITIVE_INSTANCE_SCHEMA_VERSION",
    "PrimitivePersistenceError",
    "LINK_RULE_VERSION_ENGINE_BUILD_REF",
    "LINK_RULE_VERSION_SCHEMA_VERSION",
    "LinkageRulesError",
    "ORG_LINK_REPLAY_ENGINE_BUILD_REF",
    "ORG_LINK_REPLAY_SCHEMA_VERSION",
    "OrgLinkReplayError",
    "AUTHORITATIVE_WRITER_ENGINE_BUILD_REF",
    "AUTHORITATIVE_WRITER_SCHEMA_VERSION",
    "BUNDLE_EQUIVALENCE_ENGINE_BUILD_REF",
    "BUNDLE_EQUIVALENCE_SCHEMA_VERSION",
    "BundleEquivalenceError",
    "BOUNDARY_CHECKS_VERSION",
    "CANDIDATE_GENERATION_ENGINE_BUILD_REF",
    "CANDIDATE_GENERATION_SCHEMA_VERSION",
    "MERGE_GOVERNANCE_ENGINE_BUILD_REF",
    "MERGE_GOVERNANCE_SCHEMA_VERSION",
    "MergeGovernanceError",
    "LINK_CLASSES_SCHEMA_VERSION",
    "MERGE_CLOSURE_LINK_CLASSES",
    "NON_TRUTH_LINK_CLASSES",
    "OrgLinkClass",
    "LINK_LEDGER_ENGINE_BUILD_REF",
    "LINK_LEDGER_RUNTIME_SCHEMA_VERSION",
    "ORG_LINK_TEMPORAL_SCHEMA_VERSION",
    "LinkLedgerInvariantError",
    "OrgLinkTemporalError",
    "PromotionInvariantError",
    "ORG_ENTITY_ENGINE_BUILD_REF",
    "ORG_ENTITY_RUNTIME_SCHEMA_VERSION",
    "PHASE04_ORG_ENTITY_NAMESPACE",
    "PHASE04_PROGRAM_FREEZE_VERSION",
    "OrgEntityKind",
    "TopologyMeaningBoundaryError",
    "normalize_link_class",
    "row_eligible_for_merge_closure_material",
    "verify_merge_closure_excludes_non_authoritative_link_classes_static",
    "append_bundle_equivalence_declaration",
    "append_org_merge",
    "create_merge_policy",
    "bundle_equivalence_public_dict",
    "cross_bundle_edge_bundles_from_link_metadata",
    "has_active_bundle_equivalence_declaration",
    "list_bundle_equivalence_declarations",
    "normalize_bundle_pair",
    "append_non_truth_org_link",
    "append_authoritative_org_link",
    "assert_org_link_validity_half_open",
    "assert_authoritative_link_material",
    "compute_authoritative_link_set_sha256",
    "compute_candidate_set_sha256",
    "create_promotion_policy",
    "find_authoritative_temporal_overlaps",
    "list_authoritative_temporal_overlap_violations_for_tenant",
    "list_org_link_temporal_timeline",
    "get_org_link",
    "half_open_intervals_overlap",
    "link_public_dict",
    "org_link_temporal_axis_static_errors",
    "org_link_temporal_strip_public",
    "list_org_merges",
    "merge_public_dict",
    "list_org_links",
    "material_has_evidence_or_rule",
    "deterministic_org_entity_id",
    "get_org_entity",
    "identity_key_fingerprint",
    "list_org_entities",
    "org_entity_public_dict",
    "promote_candidate_to_authoritative_link",
    "regenerate_link_candidates",
    "upsert_org_entity",
    "validate_org_meaning_link_payload",
    "verify_authoritative_replay_hash_static",
    "verify_candidate_regen_hash_static",
    "verify_link_ledger_evidence_rule_static",
    "verify_link_ledger_soft_revocation_tombstone_static",
    "verify_org_entity_determinism_static",
    "verify_topology_meaning_boundary_static",
    "verify_human_merge_two_persona_evidence_policy_static",
    "verify_merge_rollback_via_compensating_only_static",
    "execute_org_link_replay_job",
    "get_org_link_replay_job",
    "list_completed_org_link_replay_jobs_missing_receipts",
    "list_org_link_replay_jobs",
    "org_link_replay_job_public_dict",
    "org_link_replay_receipt_public_dict",
    "verify_org_link_replay_rpl01_static",
    "compute_rules_manifest_sha256",
    "create_link_rule_version",
    "get_active_link_rule_version_by_semantic",
    "get_link_rule_version",
    "link_rule_version_public_dict",
    "list_candidate_batches_with_rule_version_reference_errors",
    "list_link_rule_version_manifest_mismatches",
    "list_link_rule_versions",
    "verify_link_rule_rule01_static",
    "append_org_primitive_instance",
    "get_org_primitive_instance",
    "list_org_primitive_instances",
    "list_org_primitive_instances_missing_evidence",
    "org_primitive_instance_public_dict",
    "verify_gp04_09_primitive_evidence_discipline_static",
    "verify_gp04_prim01_static_evidence_contract",
    "build_org_graph_projection_export_document",
    "build_org_graph_projection_v1",
    "org_graph_projection_canonical_json_bytes",
    "org_graph_projection_stable_hash_sha256",
    "validate_org_graph_projection_v1_shape",
    "verify_gp04_10_graph_boundary_export_contract_static",
    "verify_gp04_exp01_export_hash_determinism_static",
    "verify_org_graph_export_forbidden_leakage",
    "verify_org_graph_projection_twice_same_hash",
    "append_org_ambiguity_record",
    "count_open_org_ambiguity_records",
    "get_org_ambiguity_record",
    "list_org_ambiguity_records",
    "list_org_ambiguity_records_invalid_entity_refs",
    "org_ambiguity_record_public_dict",
    "verify_gp04_amb01_org_ambiguity_integrity_static",
    "list_org_identity_verification_runs",
    "org_verification_run_public_dict",
    "run_org_identity_verification",
    "verify_gp04_ver01_phase04_catalog_coherence_static",
    "org_failure_case_public_dict",
    "org_remediation_validation_public_dict",
    "recompute_org_derived_failure_cases",
    "sync_org_failure_cases",
    "validate_org_remediation",
    "verify_gp04_19_org_failure_registry_sync",
    "build_identity_control_plane",
    "verify_gp04_18_org_control_plane_replay_freshness",
    "verify_gp04_21_identity_control_plane_aggregate",
    "verify_identity_control_plane_v1_shape",
]
